graph TD;
    projector-audio-level-indicator-->projector-client-object-api;
    projector-blogview-->projector-client-object-api;
    projector-calendar-->projector-client-object-api;
    projector-chart-->projector-client-object-api;
    projector-chat-->projector-client-object-api;
    projector-client-core-->projector-client-communication;
    projector-client-core-->projector-client-object-api;
    projector-client-core-components-->projector-client-communication;
    projector-client-core-components-->projector-client-object-api;
    projector-document-viewer-->projector-client-object-api;
    projector-elegant-panel-->projector-client-object-api;
    projector-file-field-->projector-client-object-api;
    projector-file-field-->projector-progress-indicator;
    projector-grid-form-->projector-client-object-api;
    projector-grid-template-->projector-client-object-api;
    projector-infinite-scrolling-components-->projector-client-object-api;
    projector-map-->projector-client-object-api;
    projector-mediasoup-client-->projector-client-object-api;
    projector-mobile-layout-->projector-client-object-api;
    projector-mobile-layout-->projector-progress-display;
    projector-mustache-template-->projector-client-object-api;
    projector-notification-->projector-client-object-api;
    projector-notification-bar-->projector-client-object-api;
    projector-notification-bar-->projector-progress-indicator;
    projector-progress-display-->projector-client-object-api;
    projector-progress-display-->projector-progress-indicator;
    projector-progress-indicator-->projector-client-object-api;
    projector-shaka-player-->projector-client-object-api;
    projector-side-drawer-->projector-client-object-api;
    projector-timegraph-->projector-client-object-api;
    projector-combobox-->projector-client-object-api;
    projector-video-player-->projector-client-object-api;
    projector-workspace-layout-->projector-client-object-api;
