@startuml
skinparam defaultTextAlignment center
skinparam rectangle {
  BackgroundColor<<optional>> beige
  BackgroundColor<<test>> lightGreen
  BackgroundColor<<runtime>> lightBlue
  BackgroundColor<<provided>> lightGray
}
rectangle "projector-common\n" as org_teamapps_projector_common_jar_compile
rectangle "teamapps-commons\n" as org_teamapps_teamapps_commons_jar_compile
rectangle "projector-dto-dsl\n" as org_teamapps_projector_dto_dsl_jar_compile
rectangle "projector-client-communication\n" as org_teamapps_projector_client_communication_jar_compile
rectangle "projector-dto-base\n" as org_teamapps_projector_dto_base_jar_compile
rectangle "projector-client-object-api\n" as org_teamapps_projector_client_object_api_jar_compile
rectangle "projector-icon\n" as org_teamapps_projector_icon_jar_compile
rectangle "projector-client-core\n" as org_teamapps_projector_client_core_jar_compile
rectangle "projector-grid-template\n" as org_teamapps_projector_grid_template_jar_compile
rectangle "projector-mustache-template\n" as org_teamapps_projector_mustache_template_jar_compile
rectangle "projector-client-core-components\n" as org_teamapps_projector_client_core_components_jar_compile
rectangle "projector-script\n" as org_teamapps_projector_script_jar_compile
rectangle "projector-stylesheet\n" as org_teamapps_projector_stylesheet_jar_compile
rectangle "projector-progress-indicator\n" as org_teamapps_projector_progress_indicator_jar_compile
rectangle "projector-notification\n" as org_teamapps_projector_notification_jar_compile
rectangle "projector-progress-display\n" as org_teamapps_projector_progress_display_jar_compile
rectangle "projector-mobile-layout\n" as org_teamapps_projector_mobile_layout_jar_compile
rectangle "projector-notification-bar\n" as org_teamapps_projector_notification_bar_jar_compile
rectangle "projector-tree-components\n" as org_teamapps_projector_tree_components_jar_compile
rectangle "projector-infinite-scrolling-components\n" as org_teamapps_projector_infinite_scrolling_components_jar_compile
rectangle "projector-material-icon-provider\n" as org_teamapps_projector_material_icon_provider_jar_compile
rectangle "projector-icon\n" as org_teamapps_projector_icon_jar_provided<<provided>>
rectangle "projector-common\n" as org_teamapps_projector_common_jar_provided<<provided>>
rectangle "teamapps-commons\n" as org_teamapps_teamapps_commons_jar_provided<<provided>>
rectangle "projector-calendar\n" as org_teamapps_projector_calendar_jar_compile
rectangle "projector-document-viewer\n" as org_teamapps_projector_document_viewer_jar_compile
rectangle "projector-elegant-panel\n" as org_teamapps_projector_elegant_panel_jar_compile
rectangle "projector-file-field\n" as org_teamapps_projector_file_field_jar_compile
rectangle "projector-timegraph\n" as org_teamapps_projector_timegraph_jar_compile
rectangle "projector-workspace-layout\n" as org_teamapps_projector_workspace_layout_jar_compile
rectangle "projector-blogview\n" as org_teamapps_projector_blogview_jar_compile
rectangle "projector-map\n" as org_teamapps_projector_map_jar_compile
rectangle "projector-shaka-player\n" as org_teamapps_projector_shaka_player_jar_compile
rectangle "projector-mediasoup-client\n" as org_teamapps_projector_mediasoup_client_jar_compile
rectangle "projector-chart\n" as org_teamapps_projector_chart_jar_compile
rectangle "projector-audio-level-indicator\n" as org_teamapps_projector_audio_level_indicator_jar_compile
rectangle "projector-chat\n" as org_teamapps_projector_chat_jar_compile
rectangle "projector-collapsible\n" as org_teamapps_projector_collapsible_jar_compile
rectangle "projector-side-drawer\n" as org_teamapps_projector_side_drawer_jar_compile
rectangle "projector-video-player\n" as org_teamapps_projector_video_player_jar_compile
rectangle "projector-grid-form\n" as org_teamapps_projector_grid_form_jar_compile
rectangle "projector-application\n" as org_teamapps_projector_application_jar_compile
rectangle "projector-server-core\n" as org_teamapps_projector_server_core_jar_compile
rectangle "projector-server-jetty-embedded\n" as org_teamapps_projector_server_jetty_embedded_jar_compile
rectangle "projector-server-undertow-embedded\n" as org_teamapps_projector_server_undertow_embedded_jar_compile
rectangle "projector-session-stats-app\n" as org_teamapps_projector_session_stats_app_jar_compile
org_teamapps_projector_common_jar_compile -[#000000]-> org_teamapps_teamapps_commons_jar_compile
org_teamapps_projector_dto_dsl_jar_compile -[#000000]-> org_teamapps_projector_common_jar_compile
org_teamapps_projector_client_communication_jar_compile -[#000000]-> org_teamapps_projector_dto_dsl_jar_compile
org_teamapps_projector_client_communication_jar_compile -[#000000]-> org_teamapps_projector_dto_base_jar_compile
org_teamapps_projector_client_object_api_jar_compile -[#000000]-> org_teamapps_projector_client_communication_jar_compile
org_teamapps_projector_client_object_api_jar_compile -[#000000]-> org_teamapps_projector_icon_jar_compile
org_teamapps_projector_client_core_jar_compile -[#000000]-> org_teamapps_projector_client_communication_jar_compile
org_teamapps_projector_grid_template_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_mustache_template_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_client_core_components_jar_compile -[#000000]-> org_teamapps_projector_grid_template_jar_compile
org_teamapps_projector_script_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_stylesheet_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_progress_indicator_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_notification_jar_compile -[#000000]-> org_teamapps_projector_client_core_components_jar_compile
org_teamapps_projector_progress_display_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_mobile_layout_jar_compile -[#000000]-> org_teamapps_projector_progress_display_jar_compile
org_teamapps_projector_mobile_layout_jar_compile -[#000000]-> org_teamapps_projector_client_core_components_jar_compile
org_teamapps_projector_notification_bar_jar_compile -[#000000]-> org_teamapps_projector_client_core_components_jar_compile
org_teamapps_projector_tree_components_jar_compile -[#000000]-> org_teamapps_projector_client_core_components_jar_compile
org_teamapps_projector_infinite_scrolling_components_jar_compile -[#000000]-> org_teamapps_projector_grid_template_jar_compile
org_teamapps_projector_material_icon_provider_jar_compile -[#000000]-> org_teamapps_projector_icon_jar_provided
org_teamapps_projector_common_jar_provided -[#000000]-> org_teamapps_teamapps_commons_jar_provided
org_teamapps_projector_material_icon_provider_jar_compile -[#000000]-> org_teamapps_projector_common_jar_provided
org_teamapps_projector_calendar_jar_compile -[#000000]-> org_teamapps_projector_client_core_components_jar_compile
org_teamapps_projector_calendar_jar_compile -[#000000]-> org_teamapps_projector_material_icon_provider_jar_compile
org_teamapps_projector_document_viewer_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_elegant_panel_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_file_field_jar_compile -[#000000]-> org_teamapps_projector_material_icon_provider_jar_compile
org_teamapps_projector_file_field_jar_compile -[#000000]-> org_teamapps_projector_client_core_components_jar_compile
org_teamapps_projector_timegraph_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_workspace_layout_jar_compile -[#000000]-> org_teamapps_projector_progress_display_jar_compile
org_teamapps_projector_workspace_layout_jar_compile -[#000000]-> org_teamapps_projector_client_core_components_jar_compile
org_teamapps_projector_blogview_jar_compile -[#000000]-> org_teamapps_projector_client_core_components_jar_compile
org_teamapps_projector_map_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_shaka_player_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_mediasoup_client_jar_compile -[#000000]-> org_teamapps_projector_client_core_components_jar_compile
org_teamapps_projector_chart_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_audio_level_indicator_jar_compile -[#000000]-> org_teamapps_projector_client_core_components_jar_compile
org_teamapps_projector_chat_jar_compile -[#000000]-> org_teamapps_projector_client_core_components_jar_compile
org_teamapps_projector_chat_jar_compile -[#000000]-> org_teamapps_projector_material_icon_provider_jar_compile
org_teamapps_projector_collapsible_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_side_drawer_jar_compile -[#000000]-> org_teamapps_projector_client_core_components_jar_compile
org_teamapps_projector_video_player_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_grid_form_jar_compile -[#000000]-> org_teamapps_projector_client_core_components_jar_compile
org_teamapps_projector_application_jar_compile -[#000000]-> org_teamapps_projector_workspace_layout_jar_compile
org_teamapps_projector_application_jar_compile -[#000000]-> org_teamapps_projector_mobile_layout_jar_compile
org_teamapps_projector_application_jar_compile -[#000000]-> org_teamapps_projector_material_icon_provider_jar_compile
org_teamapps_projector_server_core_jar_compile -[#000000]-> org_teamapps_projector_client_core_jar_compile
org_teamapps_projector_server_core_jar_compile -[#000000]-> org_teamapps_projector_client_core_components_jar_compile
org_teamapps_projector_server_core_jar_compile -[#000000]-> org_teamapps_projector_material_icon_provider_jar_compile
org_teamapps_projector_server_jetty_embedded_jar_compile -[#000000]-> org_teamapps_projector_server_core_jar_compile
org_teamapps_projector_server_undertow_embedded_jar_compile -[#000000]-> org_teamapps_projector_server_core_jar_compile
org_teamapps_projector_server_undertow_embedded_jar_compile -[#000000]-> org_teamapps_projector_notification_jar_compile
org_teamapps_projector_session_stats_app_jar_compile -[#000000]-> org_teamapps_projector_infinite_scrolling_components_jar_compile
org_teamapps_projector_session_stats_app_jar_compile -[#000000]-> org_teamapps_projector_server_core_jar_compile
org_teamapps_projector_session_stats_app_jar_compile -[#000000]-> org_teamapps_projector_application_jar_compile
org_teamapps_projector_session_stats_app_jar_compile -[#000000]-> org_teamapps_projector_tree_components_jar_compile
@enduml