@startuml
skinparam defaultTextAlignment center
skinparam rectangle {
  BackgroundColor<<optional>> beige
  BackgroundColor<<test>> lightGreen
  BackgroundColor<<runtime>> lightBlue
  BackgroundColor<<provided>> lightGray
}
rectangle "projector-common\n" as org_teamapps_projector_common_jar_compile
rectangle "teamapps-commons\n" as org_teamapps_teamapps_commons_jar_compile
rectangle "projector-dto-dsl\n" as org_teamapps_projector_dto_dsl_jar_compile
rectangle "projector-client-communication\n" as org_teamapps_projector_client_communication_jar_compile
rectangle "projector-dto-base\n" as org_teamapps_projector_dto_base_jar_compile
rectangle "projector-client-object-api\n" as org_teamapps_projector_client_object_api_jar_compile
rectangle "projector-icon\n" as org_teamapps_projector_icon_jar_compile
rectangle "projector-grid-template\n" as org_teamapps_projector_grid_template_jar_compile
rectangle "projector-script\n" as org_teamapps_projector_script_jar_compile
rectangle "projector-client-core-components\n" as org_teamapps_projector_client_core_components_jar_compile
rectangle "projector-collapsible\n" as org_teamapps_projector_collapsible_jar_compile
rectangle "projector-side-drawer\n" as org_teamapps_projector_side_drawer_jar_compile
org_teamapps_projector_common_jar_compile -[#000000]-> org_teamapps_teamapps_commons_jar_compile
org_teamapps_projector_dto_dsl_jar_compile -[#000000]-> org_teamapps_projector_common_jar_compile
org_teamapps_projector_client_communication_jar_compile -[#000000]-> org_teamapps_projector_dto_dsl_jar_compile
org_teamapps_projector_client_communication_jar_compile -[#000000]-> org_teamapps_projector_dto_base_jar_compile
org_teamapps_projector_client_object_api_jar_compile -[#000000]-> org_teamapps_projector_client_communication_jar_compile
org_teamapps_projector_client_object_api_jar_compile -[#000000]-> org_teamapps_projector_icon_jar_compile
org_teamapps_projector_grid_template_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_script_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_client_core_components_jar_compile -[#000000]-> org_teamapps_projector_grid_template_jar_compile
org_teamapps_projector_client_core_components_jar_compile -[#000000]-> org_teamapps_projector_script_jar_compile
org_teamapps_projector_collapsible_jar_compile -[#000000]-> org_teamapps_projector_client_object_api_jar_compile
org_teamapps_projector_side_drawer_jar_compile -[#000000]-> org_teamapps_projector_client_core_components_jar_compile
@enduml