/*-
 * ========================LICENSE_START=================================
 * TeamApps
 * ---
 * Copyright (C) 2014 - 2019 TeamApps.org
 * ---
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =========================LICENSE_END==================================
 */
package org.teamapps.icons.api;

import java.util.Arrays;

public enum Icons implements SimpleIcon {

	ADD("add"),
	ADDRESS_BOOK("address_book"),
	ADHESIVE_TAPE("adhesive_tape"),
	AIR_TUBE_CARRIER("air_tube_carrier"),
	AIRBRUSH("airbrush"),
	AIRPLANE("airplane"),
	AIRPLANE2("airplane2"),
	AIRPLANE2_LANDING("airplane2_landing"),
	AIRPLANE2_STARTING("airplane2_starting"),
	AIRSHIP("airship"),
	ALARM("alarm"),
	ALARMCLOCK("alarmclock"),
	AMBULANCE("ambulance"),
	AMMUNITION_BOX_CLOSED("ammunition_box_closed"),
	AMMUNITION_BOX_OPEN("ammunition_box_open"),
	ANCHOR("anchor"),
	ANGEL("angel"),
	ANTENNA("antenna"),
	APPLE("apple"),
	APPLE_BITE("apple_bite"),
	ARMOUR("armour"),
	ARMY_KNIFE("army_knife"),
	ARROW_AROUND("arrow_around"),
	ARROW_BARRIER("arrow_barrier"),
	ARROW_CIRCLE("arrow_circle"),
	ARROW_CIRCLE2("arrow_circle2"),
	ARROW_CROSS("arrow_cross"),
	ARROW_CURVE_LEFT("arrow_curve_left"),
	ARROW_DOWN("arrow_down"),
	ARROW_DOWN_LEFT("arrow_down_left"),
	ARROW_DOWN_RIGHT("arrow_down_right"),
	ARROW_FORK("arrow_fork"),
	ARROW_FORK2("arrow_fork2"),
	ARROW_FROM("arrow_from"),
	ARROW_INTO("arrow_into"),
	ARROW_JOIN("arrow_join"),
	ARROW_JOIN2("arrow_join2"),
	ARROW_JUNCTION("arrow_junction"),
	ARROW_LEFT("arrow_left"),
	ARROW_LOOP("arrow_loop"),
	ARROW_LOOP2("arrow_loop2"),
	ARROW_LOOP3("arrow_loop3"),
	ARROW_MERGE("arrow_merge"),
	ARROW_MERGE2("arrow_merge2"),
	ARROW_MIX("arrow_mix"),
	ARROW_OUT("arrow_out"),
	ARROW_OVER("arrow_over"),
	ARROW_RIGHT("arrow_right"),
	ARROW_SHUFFLE("arrow_shuffle"),
	ARROW_SPREAD("arrow_spread"),
	ARROW_SPREAD2("arrow_spread2"),
	ARROW_SQUIGGLY("arrow_squiggly"),
	ARROW_THROUGH("arrow_through"),
	ARROW_TO("arrow_to"),
	ARROW_TURN_LEFT("arrow_turn_left"),
	ARROW_U_TURN("arrow_u_turn"),
	ARROW_UP("arrow_up"),
	ARROW_UP_LEFT("arrow_up_left"),
	ARROW_UP_RIGHT("arrow_up_right"),
	ASHTRAY_CIGARETTE("ashtray_cigarette"),
	ASTROLOGER("astrologer"),
	ASTRONAUT("astronaut"),
	ATHLETE("athlete"),
	ATM("atm"),
	ATOM("atom"),
	ATOM2("atom2"),
	AUCTION_HAMMER("auction_hammer"),
	AUDIO_CASSETTE("audio_cassette"),
	AXE("axe"),
	BABY("baby"),
	BACK("back"),
	BACKPACK("backpack"),
	BACON("bacon"),
	BACTERIA("bacteria"),
	BADMINTON_RACKET("badminton_racket"),
	BAG("bag"),
	BAGS("bags"),
	BALLOON("balloon"),
	BALLOONS("balloons"),
	BALLPEN("ballpen"),
	BANANA("banana"),
	BAND_AID("band_aid"),
	BANK_BUILDING("bank_building"),
	BARCODE("barcode"),
	BARCODE_SCANNER("barcode_scanner"),
	BARREL("barrel"),
	BARRELS("barrels"),
	BARRIER_CLOSED("barrier_closed"),
	BARRIER_OPEN("barrier_open"),
	BASEBALL("baseball"),
	BASEBALL_BAT("baseball_bat"),
	BASKETBALL("basketball"),
	BASKETBALL_HOOP("basketball_hoop"),
	BATTERY_CHARGE("battery_charge"),
	BATTERY_PLUS_MINUS("battery_plus_minus"),
	BATTERY_STATUS0("battery_status0"),
	BATTERY_STATUS1("battery_status1"),
	BATTERY_STATUS2("battery_status2"),
	BATTERY_STATUS3("battery_status3"),
	BATTERY_STATUS4("battery_status4"),
	BATTERY_STATUS5("battery_status5"),
	BEAKER("beaker"),
	BEAKER2("beaker2"),
	BEAR("bear"),
	BED("bed"),
	BED_EMPTY("bed_empty"),
	BEER_BOTTLE("beer_bottle"),
	BEER_GARDEN_TABLE("beer_garden_table"),
	BEER_GLASS("beer_glass"),
	BEER_MUG("beer_mug"),
	BELL("bell"),
	BELL2("bell2"),
	BEVERAGE_CAN("beverage_can"),
	BEVERAGE_CAN_EMPTY("beverage_can_empty"),
	BIBLE("bible"),
	BICYCLE("bicycle"),
	BICYCLIST("bicyclist"),
	BILLBOARD_EMPTY("billboard_empty"),
	BINOCULAR("binocular"),
	BIRD("bird"),
	BLACKBOARD("blackboard"),
	BLENDER("blender"),
	BLOOD_BAG("blood_bag"),
	BLOT("blot"),
	BODY_SCALE("body_scale"),
	BOLT("bolt"),
	BOMB("bomb"),
	BOMB2("bomb2"),
	BONE("bone"),
	BOOK("book"),
	BOOK_BOOKMARK("book_bookmark"),
	BOOK_HEADPHONES("book_headphones"),
	BOOK_OPEN("book_open"),
	BOOK_TELEPHONE("book_telephone"),
	BOOKKEEPER("bookkeeper"),
	BOOKMARK("bookmark"),
	BOOKMARKS("bookmarks"),
	BOOKS("books"),
	BOOMBOX("boombox"),
	BOTTLE("bottle"),
	BOTTLE_BUBBLES("bottle_bubbles"),
	BOTTLE_CRATE("bottle_crate"),
	BOTTLE_OF_PILLS("bottle_of_pills"),
	BOW_TIE("bow_tie"),
	BOWL("bowl"),
	BOWLING_BALL("bowling_ball"),
	BOWLING_PIN("bowling_pin"),
	BOWLING_PINS("bowling_pins"),
	BOX_CLOSED("box_closed"),
	BOX_INTO("box_into"),
	BOX_OPEN("box_open"),
	BOX_OUT("box_out"),
	BOX_SOFTWARE("box_software"),
	BOX_SURPRISE("box_surprise"),
	BOX_TALL("box_tall"),
	BOXING_GLOVE("boxing_glove"),
	BOY("boy"),
	BRAIN("brain"),
	BREAKFAST_EGG("breakfast_egg"),
	BREAKPOINT("breakpoint"),
	BREAKPOINT_SELECTION("breakpoint_selection"),
	BREAKPOINTS("breakpoints"),
	BREAKPOINTS_SELECTION("breakpoints_selection"),
	BRICK_TROWEL("brick_trowel"),
	BRICKWALL("brickwall"),
	BRIDGE("bridge"),
	BRIEFCASE("briefcase"),
	BRIEFCASE2("briefcase2"),
	BRIEFCASE2_DOCUMENT("briefcase2_document"),
	BRIEFCASE_DOCUMENT("briefcase_document"),
	BRUSH("brush"),
	BUCKET("bucket"),
	BUG("bug"),
	BUG2("bug2"),
	BUILDING_BLOCK("building_block"),
	BULL("bull"),
	BULLDOZER("bulldozer"),
	BULLET_TRAIN("bullet_train"),
	BULLETS("bullets"),
	BUOY("buoy"),
	BUS("bus"),
	BUS2("bus2"),
	BUSINESSMEN("businessmen"),
	BUSINESSPEOPLE("businesspeople"),
	BUSINESSPEOPLE2("businesspeople2"),
	BUSINESSPERSON("businessperson"),
	BUSINESSPERSON2("businessperson2"),
	BUSINESSWOMAN("businesswoman"),
	BUSINESSWOMEN("businesswomen"),
	BUTTON("button"),
	C_CLAMP("c_clamp"),
	CABINET("cabinet"),
	CABINET2("cabinet2"),
	CABINET_FLASH("cabinet_flash"),
	CABINET_OPEN("cabinet_open"),
	CABINET_WARNING("cabinet_warning"),
	CACTUS("cactus"),
	CAESAR("caesar"),
	CAKE("cake"),
	CAKE2("cake2"),
	CAKE_SLICE("cake_slice"),
	CALCULATOR("calculator"),
	CALENDAR("calendar"),
	CALENDAR_1("calendar_1"),
	CALENDAR_3("calendar_3"),
	CALENDAR_31("calendar_31"),
	CALENDAR_5("calendar_5"),
	CALENDAR_52("calendar_52"),
	CALENDAR_7("calendar_7"),
	CALENDAR_CLOCK("calendar_clock"),
	CALIBRATION_MARK("calibration_mark"),
	CALIPER("caliper"),
	CAMERA("camera"),
	CAN_CLOSED("can_closed"),
	CAN_OPEN("can_open"),
	CANDLE("candle"),
	CANDLE_HOLDER("candle_holder"),
	CANNON("cannon"),
	CAR_COMPACT("car_compact"),
	CAR_COMPACT2("car_compact2"),
	CAR_CONVERTIBLE2("car_convertible2"),
	CAR_SEDAN("car_sedan"),
	CAR_SEDAN2("car_sedan2"),
	CAR_SPORTS("car_sports"),
	CARABINER("carabiner"),
	CARD_TERMINAL("card_terminal"),
	CARD_TERMINAL2("card_terminal2"),
	CARGO_CONTAINER("cargo_container"),
	CASH_FLOW("cash_flow"),
	CASH_REGISTER("cash_register"),
	CASHIER("cashier"),
	CASK("cask"),
	CASTLE("castle"),
	CD("cd"),
	CD_BURN("cd_burn"),
	CD_CASE("cd_case"),
	CD_DRIVE("cd_drive"),
	CD_MUSIC("cd_music"),
	CD_PIRATED("cd_pirated"),
	CD_WINDOW("cd_window"),
	CENTRAL_BANK("central_bank"),
	CENTRAL_BANK_DOLLAR("central_bank_dollar"),
	CENTRAL_BANK_EURO("central_bank_euro"),
	CENTRAL_BANK_POUND("central_bank_pound"),
	CENTRAL_BANK_YEN("central_bank_yen"),
	CENTRAL_BANK_YUAN("central_bank_yuan"),
	CHAINSAW("chainsaw"),
	CHALK("chalk"),
	CHAMPAGNE_BOTTLE("champagne_bottle"),
	CHAMPAGNE_GLASS("champagne_glass"),
	CHART_AREA("chart_area"),
	CHART_BAR("chart_bar"),
	CHART_BUBBLE("chart_bubble"),
	CHART_CANDLESTICK("chart_candlestick"),
	CHART_COLUMN("chart_column"),
	CHART_COLUMN_STACKED("chart_column_stacked"),
	CHART_DONUT("chart_donut"),
	CHART_DOT("chart_dot"),
	CHART_FUNNEL("chart_funnel"),
	CHART_GANTT("chart_gantt"),
	CHART_HI_LO("chart_hi_lo"),
	CHART_LINE("chart_line"),
	CHART_PIE("chart_pie"),
	CHART_PYRAMID("chart_pyramid"),
	CHART_RADAR("chart_radar"),
	CHART_RENKO("chart_renko"),
	CHART_SPLINE("chart_spline"),
	CHART_STEP("chart_step"),
	CHECK("check"),
	CHECKBOOK("checkbook"),
	CHECKBOX("checkbox"),
	CHECKBOX_SELECTED("checkbox_selected"),
	CHECKBOX_UNCHECKED("checkbox_unchecked"),
	CHECKBOX_UNSELECTED("checkbox_unselected"),
	CHECKS("checks"),
	CHESS_PIECE_BISHOP("chess_piece_bishop"),
	CHESS_PIECE_KING("chess_piece_king"),
	CHESS_PIECE_KNIGHT("chess_piece_knight"),
	CHESS_PIECE_PAWN("chess_piece_pawn"),
	CHESS_PIECE_QUEEN("chess_piece_queen"),
	CHESS_PIECE_ROOK("chess_piece_rook"),
	CHEST("chest"),
	CHEST_INTO("chest_into"),
	CHEST_OPEN("chest_open"),
	CHEST_OPEN_FULL("chest_open_full"),
	CHEST_OUT("chest_out"),
	CHOCOLATE("chocolate"),
	CHRISTIAN_CROSS("christian_cross"),
	CHRISTMAS_BALL("christmas_ball"),
	CHURCH("church"),
	CIGARETTE("cigarette"),
	CIGARETTE_PACKET("cigarette_packet"),
	CIGARETTE_PACKET_EMPTY("cigarette_packet_empty"),
	CIRCUS("circus"),
	CLAPPERBOARD("clapperboard"),
	CLAPPERBOARD_CLOSED("clapperboard_closed"),
	CLEAVER("cleaver"),
	CLEF("clef"),
	CLIENT_NETWORK("client_network"),
	CLIENTS("clients"),
	CLIPBOARD("clipboard"),
	CLIPBOARD_CHECK_EDIT("clipboard_check_edit"),
	CLIPBOARD_CHECKS("clipboard_checks"),
	CLIPBOARD_EMPTY("clipboard_empty"),
	CLIPBOARD_PASTE("clipboard_paste"),
	CLIPBOARD_PASTE_NO_FORMAT("clipboard_paste_no_format"),
	CLOCK("clock"),
	CLOCK_BACK("clock_back"),
	CLOCK_FORWARD("clock_forward"),
	CLOSE("close"),
	CLOTHES_PIN("clothes_pin"),
	CLOUD("cloud"),
	CLOUD_DARK("cloud_dark"),
	CLOUD_DOWNLOAD("cloud_download"),
	CLOUD_FLASH("cloud_flash"),
	CLOUD_HAIL("cloud_hail"),
	CLOUD_MOON("cloud_moon"),
	CLOUD_NETWORK("cloud_network"),
	CLOUD_RAIN("cloud_rain"),
	CLOUD_REFRESH("cloud_refresh"),
	CLOUD_SNOW("cloud_snow"),
	CLOUD_SUN("cloud_sun"),
	CLOUD_UPDOWN("cloud_updown"),
	CLOUD_UPLOAD("cloud_upload"),
	CLOWN("clown"),
	COATHANGER("coathanger"),
	COCKTAIL("cocktail"),
	COCKTAIL2("cocktail2"),
	CODE("code"),
	CODE_C("code_c"),
	CODE_CPLUSPLUS("code_cplusplus"),
	CODE_CSHARP("code_csharp"),
	CODE_JAVA("code_java"),
	CODE_JAVASCRIPT("code_javascript"),
	CODE_LINE("code_line"),
	CODE_PHP("code_php"),
	CODE_RUBY("code_ruby"),
	CODE_VBASIC("code_vbasic"),
	CODES_OF_LAW("codes_of_law"),
	COFFEE_BEAN("coffee_bean"),
	COFFEE_BEANS("coffee_beans"),
	COFFEE_MACHINE("coffee_machine"),
	COFFIN("coffin"),
	COMB("comb"),
	COMPACT_CAMERA("compact_camera"),
	COMPASS("compass"),
	COMPASSES("compasses"),
	COMPRESS("compress"),
	COMPRESS2("compress2"),
	CONSOLE("console"),
	CONSOLE_NETWORK("console_network"),
	CONSTRUCTION_BARRIER("construction_barrier"),
	CONTAINERSHIP("containership"),
	CONTRACT("contract"),
	CONTRAST("contrast"),
	CONTRAST_LOW("contrast_low"),
	CONTROL_PANEL("control_panel"),
	CONTROL_PANEL2("control_panel2"),
	CONTROL_TOWER("control_tower"),
	COOK("cook"),
	COOKIES("cookies"),
	COOLING_TOWER("cooling_tower"),
	COOLING_TOWER_SMOKE("cooling_tower_smoke"),
	COPY("copy"),
	CORKSCREW("corkscrew"),
	CORRECTION_FLUID("correction_fluid"),
	COURTHOUSE("courthouse"),
	COW("cow"),
	CPU("cpu"),
	CPU2("cpu2"),
	CPU_FLASH("cpu_flash"),
	CRACK("crack"),
	CRASH_TEST_DUMMY("crash_test_dummy"),
	CREDIT_CARD("credit_card"),
	CREDIT_CARD2("credit_card2"),
	CREDIT_CARDS("credit_cards"),
	CRIMINAL("criminal"),
	CROSSBOW("crossbow"),
	CROWN("crown"),
	CRUISE_SHIP("cruise_ship"),
	CRUTCH("crutch"),
	CRYSTAL_BALL("crystal_ball"),
	CUBE_MOLECULE("cube_molecule"),
	CUBE_MOLECULE2("cube_molecule2"),
	CUBES("cubes"),
	CUP("cup"),
	CURRENCY_DOLLAR("currency_dollar"),
	CURRENCY_EURO("currency_euro"),
	CURRENCY_PLAIN("currency_plain"),
	CURRENCY_WON("currency_won"),
	CURRENCY_YEN("currency_yen"),
	CURRENCY_YUAN("currency_yuan"),
	CUT("cut"),
	DAGGER("dagger"),
	DART("dart"),
	DATA("data"),
	DATA_CLOUD("data_cloud"),
	DATA_COPY("data_copy"),
	DATA_FLOPPY_DISK("data_floppy_disk"),
	DATA_NETWORK("data_network"),
	DATA_SCROLL("data_scroll"),
	DATA_SHARED("data_shared"),
	DATA_TABLE("data_table"),
	DEBUG("debug"),
	DECK_CHAIR("deck_chair"),
	DELETE("delete"),
	DELIVERY_MAN("delivery_man"),
	DELIVERY_NOTE("delivery_note"),
	DELIVERY_TRUCK("delivery_truck"),
	DENTURE("denture"),
	DESK("desk"),
	DESK_LAMP("desk_lamp"),
	DESKTOP("desktop"),
	DETERGENT("detergent"),
	DEVIL("devil"),
	DIAMOND("diamond"),
	DIAMOND_RING("diamond_ring"),
	DICE("dice"),
	DICTATION_MICROPHONE("dictation_microphone"),
	DICTIONARY("dictionary"),
	DIE("die"),
	DISABILITY("disability"),
	DISINFECTION("disinfection"),
	DIVING_MASK("diving_mask"),
	DNA("dna"),
	DOCTOR("doctor"),
	DOCUMENT_ATTACHMENT("document_attachment"),
	DOCUMENT_CENTER("document_center"),
	DOCUMENT_CENTER_HORIZONTAL("document_center_horizontal"),
	DOCUMENT_CENTER_VERTICAL("document_center_vertical"),
	DOCUMENT_CHART("document_chart"),
	DOCUMENT_CUP("document_cup"),
	DOCUMENT_EMPTY("document_empty"),
	DOCUMENT_EMPTY_LANDSCAPE("document_empty_landscape"),
	DOCUMENT_FOOTER("document_footer"),
	DOCUMENT_GEAR("document_gear"),
	DOCUMENT_HEADER("document_header"),
	DOCUMENT_HEART("document_heart"),
	DOCUMENT_HEIGHT("document_height"),
	DOCUMENT_INFORMATION("document_information"),
	DOCUMENT_MUSIC("document_music"),
	DOCUMENT_NOTEBOOK("document_notebook"),
	DOCUMENT_ORIENTATION_LANDSCAPE("document_orientation_landscape"),
	DOCUMENT_ORIENTATION_PORTRAIT("document_orientation_portrait"),
	DOCUMENT_PAGE_NUMBER("document_page_number"),
	DOCUMENT_PINNED("document_pinned"),
	DOCUMENT_PULSE("document_pulse"),
	DOCUMENT_SELECTION("document_selection"),
	DOCUMENT_SIZE("document_size"),
	DOCUMENT_STOP("document_stop"),
	DOCUMENT_TAG("document_tag"),
	DOCUMENT_TEXT("document_text"),
	DOCUMENT_WIDTH("document_width"),
	DOCUMENT_ZIP("document_zip"),
	DOCUMENT_ZOOM_IN("document_zoom_in"),
	DOCUMENT_ZOOM_OUT("document_zoom_out"),
	DOCUMENTS_EMPTY("documents_empty"),
	DOCUMENTS_EXCHANGE("documents_exchange"),
	DOG("dog"),
	DOME_CAMERA("dome_camera"),
	DOOR_CLOSED("door_closed"),
	DOOR_EXIT("door_exit"),
	DOOR_OPEN("door_open"),
	DOT_MATRIX("dot_matrix"),
	DOWNLOAD("download"),
	DRAM("dram"),
	DRINK("drink"),
	DROP("drop"),
	DROP_DOWN_LIST("drop_down_list"),
	DRUM("drum"),
	DUDE1("dude1"),
	DUDE2("dude2"),
	DUDE3("dude3"),
	DUDE4("dude4"),
	DUDE5("dude5"),
	DUDE6("dude6"),
	DUG_WELL("dug_well"),
	DUMBBELL("dumbbell"),
	DUMP_TRUCK("dump_truck"),
	DYNAMITE("dynamite"),
	EAR("ear"),
	EARTH("earth"),
	EARTH2("earth2"),
	EARTH_LINK("earth_link"),
	EARTH_LOCATION("earth_location"),
	EARTH_MUSIC("earth_music"),
	EARTH_NETWORK("earth_network"),
	EASEL("easel"),
	EASEL_EMPTY("easel_empty"),
	EDIT("edit"),
	EIGHTBALL("eightball"),
	ELECTRIC_IRON("electric_iron"),
	ELEMENT("element"),
	ELEMENT_COPY("element_copy"),
	ELEMENT_SELECTION("element_selection"),
	ELEMENTS("elements"),
	ELEMENTS2("elements2"),
	ELEMENTS3("elements3"),
	ELEMENTS4("elements4"),
	ELEMENTS_BRANCH("elements_branch"),
	ELEMENTS_BRANCH2("elements_branch2"),
	ELEMENTS_CASCADE("elements_cascade"),
	ELEMENTS_HIERARCHY("elements_hierarchy"),
	ELEMENTS_SELECTION("elements_selection"),
	ELEMENTS_TREE("elements_tree"),
	EMERGENCY_STOP_BUTTON("emergency_stop_button"),
	EMOTICON_ANGRY("emoticon_angry"),
	EMOTICON_BLINK("emoticon_blink"),
	EMOTICON_CLOWN("emoticon_clown"),
	EMOTICON_CONFUSED("emoticon_confused"),
	EMOTICON_COOL("emoticon_cool"),
	EMOTICON_CRY("emoticon_cry"),
	EMOTICON_FROWN("emoticon_frown"),
	EMOTICON_GRIN("emoticon_grin"),
	EMOTICON_KISS("emoticon_kiss"),
	EMOTICON_SMILE("emoticon_smile"),
	EMOTICON_STRAIGHT_FACE("emoticon_straight_face"),
	EMOTICON_SURPRISED("emoticon_surprised"),
	EMOTICON_TONGUE("emoticon_tongue"),
	ENGINEER("engineer"),
	ENVELOPE2("envelope2"),
	ENVIRONMENT("environment"),
	ENVIRONMENT_NETWORK("environment_network"),
	EQUALIZER("equalizer"),
	ERASE("erase"),
	ERROR("error"),
	ESCALATOR("escalator"),
	ESCALATOR_DOWN("escalator_down"),
	ESCALATOR_UP("escalator_up"),
	EXCAVATOR("excavator"),
	EXPLOSION("explosion"),
	EYE("eye"),
	EYE_BLIND("eye_blind"),
	EYE_SCAN("eye_scan"),
	EYEGLASSES("eyeglasses"),
	FACE_SCAN("face_scan"),
	FACTORY("factory"),
	FAN("fan"),
	FANCY_CAKE("fancy_cake"),
	FAX_MACHINE("fax_machine"),
	FEEDING_BOTTLE("feeding_bottle"),
	FENCE("fence"),
	FILM("film"),
	FILM_CARTRIDGE("film_cartridge"),
	FILTER_AND_SORT("filter_and_sort"),
	FIND_AGAIN("find_again"),
	FIND_REPLACE("find_replace"),
	FIND_TEXT("find_text"),
	FINGERPRINT("fingerprint"),
	FINGERPRINT_SCAN("fingerprint_scan"),
	FIRE("fire"),
	FIRE_EXTINGUISHER("fire_extinguisher"),
	FIRE_HYDRANT("fire_hydrant"),
	FIRE_TRUCK("fire_truck"),
	FIREFIGHTER("firefighter"),
	FIREWALL("firewall"),
	FIREWALL2("firewall2"),
	FIRST_AID("first_aid"),
	FIRST_AID_BOX("first_aid_box"),
	FISH_BOWL("fish_bowl"),
	FIT_TO_HEIGHT("fit_to_height"),
	FIT_TO_SIZE("fit_to_size"),
	FIT_TO_WIDTH("fit_to_width"),
	FLAME("flame"),
	FLASH("flash"),
	FLASHLIGHT("flashlight"),
	FLATSCREEN_TV("flatscreen_tv"),
	FLOPPY_DISK("floppy_disk"),
	FLOPPY_DISK_WINDOW("floppy_disk_window"),
	FLOPPY_DISKS("floppy_disks"),
	FLOPPY_DRIVE("floppy_drive"),
	FLOWER("flower"),
	FOLDER("folder"),
	FOLDER2("folder2"),
	FOLDER3("folder3"),
	FOLDER3_DOCUMENT("folder3_document"),
	FOLDER3_MAIL("folder3_mail"),
	FOLDER3_MOVIE("folder3_movie"),
	FOLDER3_MUSIC("folder3_music"),
	FOLDER_CUBES("folder_cubes"),
	FOLDER_DOCUMENT("folder_document"),
	FOLDER_DOCUMENT2("folder_document2"),
	FOLDER_INTO("folder_into"),
	FOLDER_MOVIE("folder_movie"),
	FOLDER_MUSIC("folder_music"),
	FOLDER_NETWORK("folder_network"),
	FOLDER_OPEN("folder_open"),
	FOLDER_OUT("folder_out"),
	FOLDER_SHARED("folder_shared"),
	FOLDER_WINDOW("folder_window"),
	FOLDER_ZIP("folder_zip"),
	FOLDERS("folders"),
	FOLDERS2("folders2"),
	FOLDING_RULE("folding_rule"),
	FONT("font"),
	FONT_STYLE_BOLD("font_style_bold"),
	FONT_STYLE_ITALICS("font_style_italics"),
	FONT_STYLE_NORMAL("font_style_normal"),
	FONT_STYLE_STRIKETHROUGH("font_style_strikethrough"),
	FONT_STYLE_SUBSCRIPT("font_style_subscript"),
	FONT_STYLE_SUPERSCRIPT("font_style_superscript"),
	FONT_STYLE_UNDERLINE("font_style_underline"),
	FOOTBALL("football"),
	FORKLIFT("forklift"),
	FORM("form"),
	FORMULA("formula"),
	FORTRESS_TOWER("fortress_tower"),
	FOUNTAIN_PEN("fountain_pen"),
	FRIED_EGG("fried_egg"),
	FRIED_EGG_BACON("fried_egg_bacon"),
	FRONT("front"),
	FUEL_DISPENSER("fuel_dispenser"),
	FUNNEL("funnel"),
	GALLOWS("gallows"),
	GAMBLING_CHIP("gambling_chip"),
	GAMBLING_CHIPS("gambling_chips"),
	GAMBLING_CHIPS2("gambling_chips2"),
	GAMEPAD("gamepad"),
	GARBAGE("garbage"),
	GARBAGE2("garbage2"),
	GARBAGE_CAN("garbage_can"),
	GARBAGE_CONTAINER("garbage_container"),
	GARBAGE_FULL("garbage_full"),
	GARBAGE_HALF_FULL("garbage_half_full"),
	GARBAGE_MAKE_EMPTY("garbage_make_empty"),
	GARBAGE_OVERFLOW("garbage_overflow"),
	GAS_CYLINDER("gas_cylinder"),
	GAUGE("gauge"),
	GAUNTLET("gauntlet"),
	GAUZE_BANDAGE("gauze_bandage"),
	GEARWHEEL("gearwheel"),
	GEARWHEELS("gearwheels"),
	GEIGER_COUNTER("geiger_counter"),
	GENIUS("genius"),
	GHOST("ghost"),
	GIFT("gift"),
	GIRL("girl"),
	GLASS_CRACKED("glass_cracked"),
	GLASS_FORK("glass_fork"),
	GLASSES_3D("glasses_3d"),
	GLOBE("globe"),
	GOAL("goal"),
	GOAL_BALL("goal_ball"),
	GOLD_BAR("gold_bar"),
	GOLD_BARS("gold_bars"),
	GOLDFISH("goldfish"),
	GOLF_BALL("golf_ball"),
	GOLF_CLUB_IRON("golf_club_iron"),
	GOLF_CLUB_PUTTER("golf_club_putter"),
	GOLF_CLUB_WOOD("golf_club_wood"),
	GOLF_FLAG("golf_flag"),
	GPS("gps"),
	GRADUATE("graduate"),
	GRADUATION_HAT("graduation_hat"),
	GRADUATION_HAT2("graduation_hat2"),
	GRAND_PIANO("grand_piano"),
	GRAPH("graph"),
	GRAPH_CLAW("graph_claw"),
	GRAPH_CONNECTION("graph_connection"),
	GRAPH_CONNECTION_DIRECTED("graph_connection_directed"),
	GRAPH_FORK("graph_fork"),
	GRAPH_FORK2("graph_fork2"),
	GRAPH_FROM("graph_from"),
	GRAPH_NODE("graph_node"),
	GRAPH_SELF_LOOP("graph_self_loop"),
	GRAPH_SQUARE("graph_square"),
	GRAPH_STAR("graph_star"),
	GRAPH_TO("graph_to"),
	GRAPH_TRIANGLE("graph_triangle"),
	GRAPHICS_TABLET("graphics_tablet"),
	GRENADE("grenade"),
	GUARD("guard"),
	GUILLOTINE("guillotine"),
	GUITAR("guitar"),
	GUN("gun"),
	HAIR_DRYER("hair_dryer"),
	HAMBURGER("hamburger"),
	HAMMER("hammer"),
	HAMMER2("hammer2"),
	HAND_CARD("hand_card"),
	HAND_COUNT_FOUR("hand_count_four"),
	HAND_COUNT_ONE("hand_count_one"),
	HAND_COUNT_THREE("hand_count_three"),
	HAND_COUNT_ZERO("hand_count_zero"),
	HAND_DRILL("hand_drill"),
	HAND_FIST("hand_fist"),
	HAND_FOUR("hand_four"),
	HAND_GUN("hand_gun"),
	HAND_MONEY("hand_money"),
	HAND_OFFER("hand_offer"),
	HAND_PAPER("hand_paper"),
	HAND_POINT_LEFT("hand_point_left"),
	HAND_POINT_LEFT2("hand_point_left2"),
	HAND_POINT_RIGHT("hand_point_right"),
	HAND_POINT_RIGHT2("hand_point_right2"),
	HAND_POINT_UP("hand_point_up"),
	HAND_POINT_UP2("hand_point_up2"),
	HAND_PUMP("hand_pump"),
	HAND_SPREAD("hand_spread"),
	HAND_STOP2("hand_stop2"),
	HAND_THUMB_DOWN("hand_thumb_down"),
	HAND_THUMB_UP("hand_thumb_up"),
	HAND_TOUCH("hand_touch"),
	HAND_TRUCK("hand_truck"),
	HAND_TRUCK_BAG("hand_truck_bag"),
	HAND_TRUCK_BOX("hand_truck_box"),
	HAND_TRUCK_SUITCASE("hand_truck_suitcase"),
	HANDBAG("handbag"),
	HANDCUFFS("handcuffs"),
	HANDHELD_DEVICE("handheld_device"),
	HANDSAW("handsaw"),
	HANDSHAKE("handshake"),
	HARD_DRIVE("hard_drive"),
	HARD_DRIVE_NETWORK("hard_drive_network"),
	HARDHAT("hardhat"),
	HAT("hat"),
	HAT2("hat2"),
	HEADPHONES("headphones"),
	HEADSET("headset"),
	HEADSTONE("headstone"),
	HEART("heart"),
	HEART_BROKEN("heart_broken"),
	HEARTBEAT("heartbeat"),
	HELICOPTER("helicopter"),
	HELMET("helmet"),
	HELP_EARTH("help_earth"),
	HISTORY("history"),
	HISTORY2("history2"),
	HOCKEY_PUCK("hockey_puck"),
	HOCKEY_STICK("hockey_stick"),
	HOLE_PUNCH("hole_punch"),
	HOLMES("holmes"),
	HOME("home"),
	HOME_FIRE("home_fire"),
	HOME_LOCK("home_lock"),
	HOME_WATER("home_water"),
	HORSE("horse"),
	HOSPITAL("hospital"),
	HOT_AIR_BALLOON("hot_air_balloon"),
	HOTEL("hotel"),
	HOURGLASS("hourglass"),
	HOUSE_FRAMEWORK("house_framework"),
	HOUSES("houses"),
	HTML_TAG("html_tag"),
	HTML_TAG2("html_tag2"),
	I_BEAM("i-beam"),
	I_BEAMS("i-beams"),
	ICE_CREAM("ice_cream"),
	ICE_CREAM2("ice_cream2"),
	ICECUBE("icecube"),
	ID_BADGE("id_badge"),
	ID_CARD("id_card"),
	ID_CARDS("id_cards"),
	IGLOO("igloo"),
	INBOX("inbox"),
	INBOX_EMPTY("inbox_empty"),
	INBOX_FULL("inbox_full"),
	INBOX_INTO("inbox_into"),
	INBOX_OUT("inbox_out"),
	INDENT_DECREASE("indent_decrease"),
	INDENT_INCREASE("indent_increase"),
	INDEX("index"),
	INDEX2("index2"),
	INDUSTRIAL_MACHINE("industrial_machine"),
	INDUSTRIAL_ROBOT("industrial_robot"),
	INFORMATION("information"),
	INFUSION_DRIP("infusion_drip"),
	INJECTION("injection"),
	INKPOT("inkpot"),
	INSTALL("install"),
	INVOICE("invoice"),
	INVOICE_DOLLAR("invoice_dollar"),
	INVOICE_EURO("invoice_euro"),
	JACKHAMMER("jackhammer"),
	JAR("jar"),
	JAR_COFFEE_BEAN("jar_coffee_bean"),
	JAR_COOKIES("jar_cookies"),
	JAR_EARTH("jar_earth"),
	JERRYCAN("jerrycan"),
	JOYSTICK("joystick"),
	JUDGE("judge"),
	KEY("key"),
	KEY2("key2"),
	KEY3("key3"),
	KEYBOARD("keyboard"),
	KEYBOARD_KEY_0("keyboard_key_0"),
	KEYBOARD_KEY_1("keyboard_key_1"),
	KEYBOARD_KEY_2("keyboard_key_2"),
	KEYBOARD_KEY_3("keyboard_key_3"),
	KEYBOARD_KEY_4("keyboard_key_4"),
	KEYBOARD_KEY_5("keyboard_key_5"),
	KEYBOARD_KEY_6("keyboard_key_6"),
	KEYBOARD_KEY_7("keyboard_key_7"),
	KEYBOARD_KEY_8("keyboard_key_8"),
	KEYBOARD_KEY_9("keyboard_key_9"),
	KEYBOARD_KEY_A("keyboard_key_a"),
	KEYBOARD_KEY_B("keyboard_key_b"),
	KEYBOARD_KEY_C("keyboard_key_c"),
	KEYBOARD_KEY_CLOCK("keyboard_key_clock"),
	KEYBOARD_KEY_D("keyboard_key_d"),
	KEYBOARD_KEY_DOWN("keyboard_key_down"),
	KEYBOARD_KEY_E("keyboard_key_e"),
	KEYBOARD_KEY_EMPTY("keyboard_key_empty"),
	KEYBOARD_KEY_ENTER("keyboard_key_enter"),
	KEYBOARD_KEY_F("keyboard_key_f"),
	KEYBOARD_KEY_G("keyboard_key_g"),
	KEYBOARD_KEY_H("keyboard_key_h"),
	KEYBOARD_KEY_I("keyboard_key_i"),
	KEYBOARD_KEY_J("keyboard_key_j"),
	KEYBOARD_KEY_K("keyboard_key_k"),
	KEYBOARD_KEY_L("keyboard_key_l"),
	KEYBOARD_KEY_LEFT("keyboard_key_left"),
	KEYBOARD_KEY_M("keyboard_key_m"),
	KEYBOARD_KEY_MINUS("keyboard_key_minus"),
	KEYBOARD_KEY_N("keyboard_key_n"),
	KEYBOARD_KEY_O("keyboard_key_o"),
	KEYBOARD_KEY_P("keyboard_key_p"),
	KEYBOARD_KEY_PLUS("keyboard_key_plus"),
	KEYBOARD_KEY_Q("keyboard_key_q"),
	KEYBOARD_KEY_R("keyboard_key_r"),
	KEYBOARD_KEY_RIGHT("keyboard_key_right"),
	KEYBOARD_KEY_S("keyboard_key_s"),
	KEYBOARD_KEY_SHIFT("keyboard_key_shift"),
	KEYBOARD_KEY_SPEAKER("keyboard_key_speaker"),
	KEYBOARD_KEY_T("keyboard_key_t"),
	KEYBOARD_KEY_U("keyboard_key_u"),
	KEYBOARD_KEY_UP("keyboard_key_up"),
	KEYBOARD_KEY_V("keyboard_key_v"),
	KEYBOARD_KEY_W("keyboard_key_w"),
	KEYBOARD_KEY_X("keyboard_key_x"),
	KEYBOARD_KEY_Y("keyboard_key_y"),
	KEYBOARD_KEY_Z("keyboard_key_z"),
	KEYBOARD_WIRELESS("keyboard_wireless"),
	KEYHOLE("keyhole"),
	KEYPAD("keypad"),
	KEYS("keys"),
	KIDNEY_DISH("kidney_dish"),
	KNIFE("knife"),
	KNIFE_FORK("knife_fork"),
	KNIFE_FORK_SPOON("knife_fork_spoon"),
	KNOT("knot"),
	LADDER("ladder"),
	LANTERN("lantern"),
	LANTERN_ON("lantern_on"),
	LAPTOP("laptop"),
	LASER_POINTER("laser_pointer"),
	LAUNDRY_MACHINE("laundry_machine"),
	LAUREL_WREATH("laurel_wreath"),
	LAYOUT("layout"),
	LAYOUT_CENTER("layout_center"),
	LAYOUT_EAST("layout_east"),
	LAYOUT_HORIZONTAL("layout_horizontal"),
	LAYOUT_NORTH("layout_north"),
	LAYOUT_NORTHEAST("layout_northeast"),
	LAYOUT_NORTHWEST("layout_northwest"),
	LAYOUT_SOUTH("layout_south"),
	LAYOUT_SOUTHEAST("layout_southeast"),
	LAYOUT_SOUTHWEST("layout_southwest"),
	LAYOUT_VERTICAL("layout_vertical"),
	LAYOUT_WEST("layout_west"),
	LEAF("leaf"),
	LECTERN("lectern"),
	LECTURE("lecture"),
	LED("led"),
	LEMON("lemon"),
	LEMONADE_GLASS("lemonade_glass"),
	LIFEBELT("lifebelt"),
	LIGHTBULB_OFF("lightbulb_off"),
	LIGHTBULB_ON("lightbulb_on"),
	LIGHTHOUSE("lighthouse"),
	LINE_BREAK("line_break"),
	LINE_SPACING_PARAGRAPH("line_spacing_paragraph"),
	LINE_SPACING_TEXT("line_spacing_text"),
	LINK("link"),
	LINK_BROKEN("link_broken"),
	LIPSTICK("lipstick"),
	LIST_STYLE_BULLETS("list_style_bullets"),
	LIST_STYLE_NUMBERED("list_style_numbered"),
	LIST_STYLE_ROMAN("list_style_roman"),
	LOCATION_PIN("location_pin"),
	LOCK("lock"),
	LOCK2("lock2"),
	LOCK3("lock3"),
	LOCK_OPEN("lock_open"),
	LOG("log"),
	LOG_IN("log_in"),
	LOG_OUT("log_out"),
	LOGIC_AND("logic_and"),
	LOGIC_NOT("logic_not"),
	LOGIC_OR("logic_or"),
	LOGIC_XOR("logic_xor"),
	LOGS("logs"),
	LOLLIPOP("lollipop"),
	LOUDSPEAKER("loudspeaker"),
	LOUDSPEAKER2("loudspeaker2"),
	LOUDSPEAKER3("loudspeaker3"),
	LOUDSPEAKER4("loudspeaker4"),
	LOUDSPEAKER_BOX("loudspeaker_box"),
	LOUDSPEAKER_NETWORK("loudspeaker_network"),
	LOUDSPEAKER_OFF("loudspeaker_off"),
	MAGAZINE_FOLDER("magazine_folder"),
	MAGAZINE_FOLDER_EMPTY("magazine_folder_empty"),
	MAGIC_WAND("magic_wand"),
	MAGICIAN("magician"),
	MAGNET("magnet"),
	MAGNIFYING_GLASS("magnifying_glass"),
	MAIL("mail"),
	MAIL2("mail2"),
	MAIL_ATTACHMENT("mail_attachment"),
	MAIL_BUG("mail_bug"),
	MAIL_CLOUD("mail_cloud"),
	MAIL_EARTH("mail_earth"),
	MAIL_EXCHANGE("mail_exchange"),
	MAIL_FILTER("mail_filter"),
	MAIL_FORWARD("mail_forward"),
	MAIL_INTO("mail_into"),
	MAIL_OPEN("mail_open"),
	MAIL_OPEN2("mail_open2"),
	MAIL_OUT("mail_out"),
	MAIL_REPLY("mail_reply"),
	MAIL_REPLY_ALL("mail_reply_all"),
	MAIL_SEALED("mail_sealed"),
	MAIL_VIRUS("mail_virus"),
	MAIL_WRITE("mail_write"),
	MAILBOX_EMPTY("mailbox_empty"),
	MAILBOX_FULL("mailbox_full"),
	MAILS("mails"),
	MANEKI_NEKO("maneki_neko"),
	MAP("map"),
	MAP_LOCATION("map_location"),
	MAP_LOCATION2("map_location2"),
	MAP_ROADS("map_roads"),
	MAP_ROUTE("map_route"),
	MARIONETTE("marionette"),
	MARKER("marker"),
	MARKET_STAND("market_stand"),
	MASK("mask"),
	MASKS("masks"),
	MATRYOSHKA("matryoshka"),
	MAXIMIZE("maximize"),
	MDA("mda"),
	MEASURING_CUP("measuring_cup"),
	MEDAL("medal"),
	MEDAL2("medal2"),
	MEDIA_BEGINNING("media_beginning"),
	MEDIA_EJECT("media_eject"),
	MEDIA_END("media_end"),
	MEDIA_FAST_FORWARD("media_fast_forward"),
	MEDIA_PAUSE("media_pause"),
	MEDIA_PLAY("media_play"),
	MEDIA_RECORD("media_record"),
	MEDIA_REWIND("media_rewind"),
	MEDIA_STEP_BACK("media_step_back"),
	MEDIA_STEP_FORWARD("media_step_forward"),
	MEDIA_STOP("media_stop"),
	MEDICAL_BAG("medical_bag"),
	MEGAPHONE("megaphone"),
	MEMORY("memory"),
	MEMORY_STICK("memory_stick"),
	MENORA("menora"),
	MESSAGE("message"),
	MESSAGES("messages"),
	MICROPHONE("microphone"),
	MICROPHONE2("microphone2"),
	MICROSCOPE("microscope"),
	MICROWAVE_OVEN("microwave_oven"),
	MILK("milk"),
	MINIBUS("minibus"),
	MINIMIZE("minimize"),
	MINUS("minus"),
	MIRROR_HORIZONTALLY("mirror_horizontally"),
	MIRROR_VERTICALLY("mirror_vertically"),
	MISSILE("missile"),
	MISSILE2("missile2"),
	MOBILE_CRANE("mobile_crane"),
	MOBILE_PHONE("mobile_phone"),
	MOBILE_PHONE2("mobile_phone2"),
	MOBILE_PHONE3("mobile_phone3"),
	MODEM("modem"),
	MODEM_EARTH("modem_earth"),
	MOLECULE_H2O("molecule_h2o"),
	MONEY("money"),
	MONEY2("money2"),
	MONEY_BILL_CUT("money_bill_cut"),
	MONEY_BILL_FIRE("money_bill_fire"),
	MONEY_BILLS("money_bills"),
	MONEY_COIN("money_coin"),
	MONEY_COINS("money_coins"),
	MONEY_COINS2("money_coins2"),
	MONEY_DOLLAR("money_dollar"),
	MONEY_EURO("money_euro"),
	MONEY_INTEREST("money_interest"),
	MONEY_REFUND("money_refund"),
	MONEYBAG("moneybag"),
	MONEYBAG_COINS("moneybag_coins"),
	MONEYBAG_DOLLAR("moneybag_dollar"),
	MONEYBAG_EURO("moneybag_euro"),
	MONITOR("monitor"),
	MONITOR_BRUSH("monitor_brush"),
	MONITOR_HEIGHT("monitor_height"),
	MONITOR_SIZE("monitor_size"),
	MONITOR_SLEEP("monitor_sleep"),
	MONITOR_TEST_CARD("monitor_test_card"),
	MONITOR_TOUCH("monitor_touch"),
	MONITOR_WIDTH("monitor_width"),
	MOON("moon"),
	MOON_HALF("moon_half"),
	MOSQUE("mosque"),
	MOSQUITO("mosquito"),
	MOTOR_SCOOTER("motor_scooter"),
	MOTORBIKE("motorbike"),
	MOTORCYCLE_HELMET("motorcycle_helmet"),
	MOTORCYCLIST("motorcyclist"),
	MOUSE("mouse"),
	MOUSE2("mouse2"),
	MOUSE2_LEFT_BUTTON("mouse2_left_button"),
	MOUSE2_RIGHT_BUTTON("mouse2_right_button"),
	MOUSE_LEFT_BUTTON("mouse_left_button"),
	MOUSE_POINTER("mouse_pointer"),
	MOUSE_RIGHT_BUTTON("mouse_right_button"),
	MOUSETRAP("mousetrap"),
	MOVIE("movie"),
	MOVIE_CAMERA("movie_camera"),
	MOVIES("movies"),
	MOVING_TRUCK("moving_truck"),
	MUG("mug"),
	MUG_TEA("mug_tea"),
	MULTIMETER("multimeter"),
	MULTIMETER_ANALOG("multimeter_analog"),
	MUSHROOM("mushroom"),
	MUSIC("music"),
	NAIL("nail"),
	NAV_DOWN("nav_down"),
	NAV_DOWN_LEFT("nav_down_left"),
	NAV_DOWN_RIGHT("nav_down_right"),
	NAV_LEFT("nav_left"),
	NAV_PLAIN("nav_plain"),
	NAV_REDO("nav_redo"),
	NAV_REFRESH("nav_refresh"),
	NAV_RIGHT("nav_right"),
	NAV_UNDO("nav_undo"),
	NAV_UP("nav_up"),
	NAV_UP_LEFT("nav_up_left"),
	NAV_UP_RIGHT("nav_up_right"),
	NAVIGATE_BEGINNING("navigate_beginning"),
	NAVIGATE_CHECK("navigate_check"),
	NAVIGATE_CLOSE("navigate_close"),
	NAVIGATE_CROSS("navigate_cross"),
	NAVIGATE_DOWN("navigate_down"),
	NAVIGATE_DOWN2("navigate_down2"),
	NAVIGATE_END("navigate_end"),
	NAVIGATE_LEFT("navigate_left"),
	NAVIGATE_LEFT2("navigate_left2"),
	NAVIGATE_MINUS("navigate_minus"),
	NAVIGATE_OPEN("navigate_open"),
	NAVIGATE_PLUS("navigate_plus"),
	NAVIGATE_RIGHT("navigate_right"),
	NAVIGATE_RIGHT2("navigate_right2"),
	NAVIGATE_UP("navigate_up"),
	NAVIGATE_UP2("navigate_up2"),
	NETWORK_NODE("network_node"),
	NETWORK_NODE2("network_node2"),
	NEWSPAPER("newspaper"),
	NEWTONS_CRADLE("newtons_cradle"),
	NONPROFIT("nonprofit"),
	NOSE("nose"),
	NOTE("note"),
	NOTE_BLOCK("note_block"),
	NOTE_PINNED("note_pinned"),
	NOTE_TEXT("note_text"),
	NOTEBOOK("notebook"),
	NOTEBOOK2("notebook2"),
	NOTEBOOK3("notebook3"),
	NUMERIC_KEYPAD("numeric_keypad"),
	OBJECT_ALIGNMENT_BOTTOM("object_alignment_bottom"),
	OBJECT_ALIGNMENT_CENTER("object_alignment_center"),
	OBJECT_ALIGNMENT_HORIZONTAL("object_alignment_horizontal"),
	OBJECT_ALIGNMENT_LEFT("object_alignment_left"),
	OBJECT_ALIGNMENT_RIGHT("object_alignment_right"),
	OBJECT_ALIGNMENT_TOP("object_alignment_top"),
	OBJECT_ALIGNMENT_VERTICAL("object_alignment_vertical"),
	OBJECT_BALL("object_ball"),
	OBJECT_CONE("object_cone"),
	OBJECT_CUBE("object_cube"),
	OBJECT_CYLINDER("object_cylinder"),
	OBJECTS("objects"),
	OBJECTS2("objects2"),
	OBJECTS3("objects3"),
	OBJECTS4("objects4"),
	OBJECTS_EXCHANGE("objects_exchange"),
	OBJECTS_TRANSFORM("objects_transform"),
	OBJECTS_TRANSFORM2("objects_transform2"),
	ODOMETER("odometer"),
	OFFICE_BUILDING("office_building"),
	OFFICE_BUILDING2("office_building2"),
	OFFICE_CHAIR("office_chair"),
	OIL_PLATFORM("oil_platform"),
	OIL_PUMP("oil_pump"),
	OK("ok"),
	ORANGE("orange"),
	PACEMAKER("pacemaker"),
	PACIFIER("pacifier"),
	PACKAGE("package"),
	PACKAGING_PAPER("packaging_paper"),
	PACKAGING_TAPE("packaging_tape"),
	PAGER("pager"),
	PAGODA("pagoda"),
	PAINT_BRUSH("paint_brush"),
	PAINT_BUCKET("paint_bucket"),
	PAINT_ROLLER("paint_roller"),
	PAINTERS_PALETTE("painters_palette"),
	PAINTERS_PALETTE2("painters_palette2"),
	PAINTERS_PALETTE_BRUSH("painters_palette_brush"),
	PAINTERS_PALETTE_EMPTY("painters_palette_empty"),
	PAINTING_LANDSCAPE("painting_landscape"),
	PAINTING_PORTRAIT("painting_portrait"),
	PALM_TREE("palm_tree"),
	PAN_FLUTE("pan_flute"),
	PAPER_FAN("paper_fan"),
	PAPER_JET("paper_jet"),
	PAPER_JET2("paper_jet2"),
	PAPER_LANTERN("paper_lantern"),
	PAPER_ROLL("paper_roll"),
	PAPERCLIP("paperclip"),
	PAPERCLIP2("paperclip2"),
	PARASOL("parasol"),
	PARKING_METER("parking_meter"),
	PASSPORT("passport"),
	PASSWORD_FIELD("password_field"),
	PASTOR("pastor"),
	PAWN("pawn"),
	PCI_CARD("pci_card"),
	PCI_CARD_NETWORK("pci_card_network"),
	PDA("pda"),
	PDA_WRITE("pda_write"),
	PENCIL("pencil"),
	PENS("pens"),
	PENTAGRAM("pentagram"),
	PERFUME("perfume"),
	PERSON("person"),
	PET_BOTTLE("pet_bottle"),
	PETRI_DISH("petri_dish"),
	PHONE_CONFERENCE("phone_conference"),
	PHONE_HANG_UP("phone_hang_up"),
	PHONE_PICK_UP("phone_pick_up"),
	PHONE_RECEIVER("phone_receiver"),
	PHONE_RECEIVER2("phone_receiver2"),
	PHONE_SPEAKER("phone_speaker"),
	PHONE_SPEECH_BUBBLE("phone_speech_bubble"),
	PHOTO_LANDSCAPE("photo_landscape"),
	PHOTO_PORTRAIT("photo_portrait"),
	PHOTOGRAPHIC_FILTER("photographic_filter"),
	PHOTOGRAPHIC_FILTERS("photographic_filters"),
	PHOTOS("photos"),
	PIECE("piece"),
	PIECE2("piece2"),
	PIECES("pieces"),
	PIG("pig"),
	PIGGY_BANK("piggy_bank"),
	PILL("pill"),
	PILL2("pill2"),
	PILOT("pilot"),
	PIN("pin"),
	PIN2("pin2"),
	PINEAPPLE("pineapple"),
	PIPETTE("pipette"),
	PIPETTE_TEST("pipette_test"),
	PIRATES_SHIP("pirates_ship"),
	PLANE_TOOL("plane_tool"),
	PLANET("planet"),
	PLANK("plank"),
	PLANKS("planks"),
	PLANT("plant"),
	PLATFORM_TRUCK_BOX("platform_truck_box"),
	PLATFORM_TRUCK_EMPTY("platform_truck_empty"),
	PLATFORM_TRUCK_SUITCASE("platform_truck_suitcase"),
	PLAYING_CARD_CLUBS("playing_card_clubs"),
	PLAYING_CARD_DIAMONDS("playing_card_diamonds"),
	PLAYING_CARD_HEARTS("playing_card_hearts"),
	PLAYING_CARD_SPADES("playing_card_spades"),
	PLAYING_CARDS("playing_cards"),
	PLAYING_CARDS_DECK("playing_cards_deck"),
	PLIERS("pliers"),
	PLUG("plug"),
	PLUG2("plug2"),
	PLUG_CINCH("plug_cinch"),
	PLUG_LAN("plug_lan"),
	PLUG_USB("plug_usb"),
	PLUS("plus"),
	PODIUM("podium"),
	PODIUM2("podium2"),
	POISON("poison"),
	POLICE_CAR("police_car"),
	POLICEMAN("policeman"),
	POLICEMAN_BOBBY("policeman_bobby"),
	PONTIFEX("pontifex"),
	POOL_BALLS("pool_balls"),
	PORTABLE_BARCODE_SCANNER("portable_barcode_scanner"),
	PORTFOLIO_FOLDER("portfolio_folder"),
	POST_HORN("post_horn"),
	POSTAGE_STAMP("postage_stamp"),
	POWER("power"),
	POWER_DRILL("power_drill"),
	PRECISION_KNIFE("precision_knife"),
	PRECISION_SQUARE("precision_square"),
	PRESENTATION_CHART("presentation_chart"),
	PRESENTATION_EMPTY("presentation_empty"),
	PRESS("press"),
	PRESSURE_SPRAYER("pressure_sprayer"),
	PRETZEL("pretzel"),
	PRICE_STICKER("price_sticker"),
	PRINT_CALCULATOR("print_calculator"),
	PRINT_LAYOUT_CONTINOUS("print_layout_continous"),
	PRINT_LAYOUT_SINGLE("print_layout_single"),
	PRINTER("printer"),
	PRINTER3("printer3"),
	PRINTER_NETWORK("printer_network"),
	PROGRESS_BAR("progress_bar"),
	PROJECTOR("projector"),
	PUMPKIN("pumpkin"),
	PUMPKIN_HALLOWEEN("pumpkin_halloween"),
	PUNCHING_BAG("punching_bag"),
	PURCHASE_ORDER("purchase_order"),
	PURSE("purse"),
	PYLON("pylon"),
	QUAD("quad"),
	QUESTION("question"),
	QUESTION_AND_ANSWER("question_and_answer"),
	QUOTATION_MARK("quotation_mark"),
	QUOTATION_MARK2("quotation_mark2"),
	QUOTATION_MARKS("quotation_marks"),
	RACK_SERVER("rack_server"),
	RACK_SERVER_NETWORK("rack_server_network"),
	RACK_SERVERS("rack_servers"),
	RADAR("radar"),
	RADIATION("radiation"),
	RADIO("radio"),
	RADIO_BUTTON_GROUP("radio_button_group"),
	RADIO_BUTTON_SELECTED("radio_button_selected"),
	RADIO_BUTTON_UNSELECTED("radio_button_unselected"),
	RAIN_DROPS("rain_drops"),
	RAZOR("razor"),
	REACTOR("reactor"),
	RECEIPT("receipt"),
	RECEIPT_BOOK("receipt_book"),
	RECEIPT_PRINTER("receipt_printer"),
	RECORD("record"),
	RECORD_PLAYER("record_player"),
	RECYCLE("recycle"),
	REDO("redo"),
	REFRESH("refresh"),
	REGISTRY("registry"),
	REMOTE_CONTROL("remote_control"),
	REMOTE_CONTROL2("remote_control2"),
	REPEAT("repeat"),
	RESIZE("resize"),
	RETICLE("reticle"),
	RFID_CHIP("rfid_chip"),
	RFQ("rfq"),
	ROAD_ROLLER("road_roller"),
	ROBOT("robot"),
	ROCKET("rocket"),
	ROCKING_HORSE("rocking_horse"),
	ROTATE_LEFT("rotate_left"),
	ROTATE_RIGHT("rotate_right"),
	ROULETTE_WHEEL("roulette_wheel"),
	ROUTE_SIGN("route_sign"),
	ROUTER("router"),
	RSS("rss"),
	RUBBER_STAMP("rubber_stamp"),
	SAFE("safe"),
	SAFE_INTO("safe_into"),
	SAFE_OPEN_EMPTY("safe_open_empty"),
	SAFE_OPEN_FULL("safe_open_full"),
	SAFE_OUT("safe_out"),
	SAFETY_GLASSES("safety_glasses"),
	SAFETY_PIN("safety_pin"),
	SAFETY_PIN_OPEN("safety_pin_open"),
	SAILBOAT("sailboat"),
	SALES_QUOTATION("sales_quotation"),
	SATELLITE("satellite"),
	SATELLITE_DISH("satellite_dish"),
	SAUSAGE("sausage"),
	SAVE_AS("save_as"),
	SCALES("scales"),
	SCALPEL("scalpel"),
	SCANNER("scanner"),
	SCHOOL("school"),
	SCHOOLBOY("schoolboy"),
	SCHOOLBUS("schoolbus"),
	SCHOOLBUS2("schoolbus2"),
	SCIENTIST("scientist"),
	SCOOTER("scooter"),
	SCORE_BOARD("score_board"),
	SCREWDRIVER("screwdriver"),
	SCROLL("scroll"),
	SCROLL2("scroll2"),
	SCROLL_BAR_HORIZONTAL("scroll_bar_horizontal"),
	SCROLL_BAR_VERTICAL("scroll_bar_vertical"),
	SD_CARD("sd_card"),
	SECURITY_AGENT("security_agent"),
	SECURITY_BADGE("security_badge"),
	SELECTION("selection"),
	SELECTION_DELETE("selection_delete"),
	SELECTION_FIND("selection_find"),
	SELECTION_RECYCLE("selection_recycle"),
	SELECTION_REFRESH("selection_refresh"),
	SELECTION_VIEW("selection_view"),
	SENIOR_CITIZEN("senior_citizen"),
	SENIOR_CITIZEN2("senior_citizen2"),
	SERVER("server"),
	SERVER2("server2"),
	SERVER_CLIENT("server_client"),
	SERVER_CLIENT_EXCHANGE("server_client_exchange"),
	SERVER_CLOUD("server_cloud"),
	SERVER_DOCUMENT("server_document"),
	SERVER_EARTH("server_earth"),
	SERVER_FROM_CLIENT("server_from_client"),
	SERVER_ID_CARD("server_id_card"),
	SERVER_INTO("server_into"),
	SERVER_MAIL("server_mail"),
	SERVER_MAIL_DOWNLOAD("server_mail_download"),
	SERVER_MAIL_UPLOAD("server_mail_upload"),
	SERVER_NETWORK("server_network"),
	SERVER_OUT("server_out"),
	SERVER_TO_CLIENT("server_to_client"),
	SERVICE_BELL("service_bell"),
	SET_SQUARE("set_square"),
	SEWING_MACHINE("sewing_machine"),
	SHAPE_CIRCLE("shape_circle"),
	SHAPE_ELLIPSE("shape_ellipse"),
	SHAPE_HEXAGON("shape_hexagon"),
	SHAPE_OCTAGON("shape_octagon"),
	SHAPE_PENTAGON("shape_pentagon"),
	SHAPE_RECTANGLE("shape_rectangle"),
	SHAPE_RHOMB("shape_rhomb"),
	SHAPE_SQUARE("shape_square"),
	SHAPE_TRIANGLE("shape_triangle"),
	SHAPES("shapes"),
	SHARE("share"),
	SHELF_EMPTY("shelf_empty"),
	SHELF_FULL("shelf_full"),
	SHIELD("shield"),
	SHIP1("ship1"),
	SHIP2("ship2"),
	SHIPS_WHEEL("ships_wheel"),
	SHOPPING_BAG("shopping_bag"),
	SHOPPING_BAG_FULL("shopping_bag_full"),
	SHOPPING_BASKET("shopping_basket"),
	SHOPPING_BASKET_FULL("shopping_basket_full"),
	SHOPPING_CART("shopping_cart"),
	SHOPPING_CART_FULL("shopping_cart_full"),
	SHOWER_GEL("shower_gel"),
	SHREDDER("shredder"),
	SHUTTER("shutter"),
	SHUTTLECOCK("shuttlecock"),
	SICKLE("sickle"),
	SIGN_FORBIDDEN("sign_forbidden"),
	SIGN_STOP("sign_stop"),
	SIGN_WARNING("sign_warning"),
	SIGN_WARNING_BIOHAZARD("sign_warning_biohazard"),
	SIGN_WARNING_FLAMMABLE("sign_warning_flammable"),
	SIGN_WARNING_HARMFUL("sign_warning_harmful"),
	SIGN_WARNING_RADIATION("sign_warning_radiation"),
	SIGN_WARNING_TOXIC("sign_warning_toxic"),
	SIGN_WARNING_VOLTAGE("sign_warning_voltage"),
	SIGN_YIELD("sign_yield"),
	SIGNAL_FLAG("signal_flag"),
	SIGNAL_FLAG_CHECKERED("signal_flag_checkered"),
	SIGNAL_STRENGTH_0("signal_strength_0"),
	SIGNAL_STRENGTH_1("signal_strength_1"),
	SIGNAL_STRENGTH_2("signal_strength_2"),
	SIGNAL_STRENGTH_3("signal_strength_3"),
	SIGNAL_STRENGTH_4("signal_strength_4"),
	SIGNAL_STRENGTH_5("signal_strength_5"),
	SIGNBOARD_CLOSED("signboard_closed"),
	SIGNBOARD_EMPTY("signboard_empty"),
	SIGNBOARD_FOR_RENT("signboard_for_rent"),
	SIGNBOARD_FOR_SALE("signboard_for_sale"),
	SIGNBOARD_OPEN("signboard_open"),
	SIGNBOARD_SOLD("signboard_sold"),
	SIGNPOST("signpost"),
	SIGNPOST2("signpost2"),
	SIGNPOST3("signpost3"),
	SIM_CARD("sim_card"),
	SINGER("singer"),
	SIXPACK_BEER("sixpack_beer"),
	SIZES("sizes"),
	SKATEBOARD("skateboard"),
	SKIN_COW("skin_cow"),
	SKIN_TIGER("skin_tiger"),
	SKULL("skull"),
	SKULL2("skull2"),
	SLEDGE("sledge"),
	SLIDER("slider"),
	SLINGSHOT("slingshot"),
	SMALL_TRUCK("small_truck"),
	SMARTCARD("smartcard"),
	SMARTPHONE("smartphone"),
	SMARTPHONE_CLOUD("smartphone_cloud"),
	SMS("sms"),
	SNOWFLAKE("snowflake"),
	SNOWMAN("snowman"),
	SOAP_DISPENSER("soap_dispenser"),
	SOCCER_BALL("soccer_ball"),
	SOLAR_PANEL("solar_panel"),
	SORT_19_ASCENDING("sort_19_ascending"),
	SORT_19_DESCENDING("sort_19_descending"),
	SORT_ASCENDING("sort_ascending"),
	SORT_ASCENDING2("sort_ascending2"),
	SORT_AZ_ASCENDING("sort_az_ascending"),
	SORT_AZ_ASCENDING2("sort_az_ascending2"),
	SORT_AZ_DESCENDING("sort_az_descending"),
	SORT_AZ_DESCENDING2("sort_az_descending2"),
	SORT_DESCENDING("sort_descending"),
	SORT_DESCENDING2("sort_descending2"),
	SORT_DOWN("sort_down"),
	SORT_DOWN_MINUS("sort_down_minus"),
	SORT_DOWN_PLUS("sort_down_plus"),
	SORT_UP("sort_up"),
	SORT_UP_DOWN("sort_up_down"),
	SORT_UP_DOWN2("sort_up_down2"),
	SORT_UP_DOWN_QUESTION("sort_up_down_question"),
	SORT_UP_MINUS("sort_up_minus"),
	SORT_UP_PLUS("sort_up_plus"),
	SPADE("spade"),
	SPAM("spam"),
	SPEECH_BALLOON("speech_balloon"),
	SPEECH_BALLOON_ANSWER("speech_balloon_answer"),
	SPEECH_BALLOON_QUESTION("speech_balloon_question"),
	SPELLCHECK("spellcheck"),
	SPELLCHECK2("spellcheck2"),
	SPIDER("spider"),
	SPIRIT_LEVEL("spirit_level"),
	SPONGE("sponge"),
	SPRAY_CAN("spray_can"),
	SPREADSHEET("spreadsheet"),
	SPREADSHEET_CELL("spreadsheet_cell"),
	SPREADSHEET_CHART("spreadsheet_chart"),
	SPREADSHEET_COLUMN("spreadsheet_column"),
	SPREADSHEET_DATA("spreadsheet_data"),
	SPREADSHEET_ROW("spreadsheet_row"),
	SPREADSHEET_SORT_ASCENDING("spreadsheet_sort_ascending"),
	SPREADSHEET_SORT_DESCENDING("spreadsheet_sort_descending"),
	SPREADSHEET_SUM("spreadsheet_sum"),
	SPY("spy"),
	SSD_DRIVE("ssd_drive"),
	STAIRS_DOWN("stairs_down"),
	STAIRS_UP("stairs_up"),
	STANDBY("standby"),
	STAPLER("stapler"),
	STAR("star"),
	STAR2("star2"),
	STAR_AND_CRESCENT("star_and_crescent"),
	STAR_OF_DAVID("star_of_david"),
	STEERING_WHEEL("steering_wheel"),
	STEP("step"),
	STETHOSCOPE("stethoscope"),
	STICKY_NOTE("sticky_note"),
	STICKY_NOTE_TEXT("sticky_note_text"),
	STOCK_TICKER("stock_ticker"),
	STOCKBROKER("stockbroker"),
	STOCKBROKER2("stockbroker2"),
	STOPWATCH("stopwatch"),
	STOPWATCH2("stopwatch2"),
	STORE("store"),
	STROLLER("stroller"),
	SUBMARINE("submarine"),
	SUITCASE("suitcase"),
	SUITCASE2("suitcase2"),
	SUN("sun"),
	SUN_DIMMED("sun_dimmed"),
	SUN_HALF("sun_half"),
	SUNGLASSES("sunglasses"),
	SURGEON("surgeon"),
	SURVEILLANCE_CAMERA("surveillance_camera"),
	SURVEILLANCE_CAMERA2("surveillance_camera2"),
	SWITCH2_OFF("switch2_off"),
	SWITCH2_ON("switch2_on"),
	SWITCH3_OFF("switch3_off"),
	SWITCH3_ON("switch3_on"),
	SWITCH_OFF("switch_off"),
	SWITCH_ON("switch_on"),
	SWORD("sword"),
	SYMBOL_AT("symbol_at"),
	SYMBOL_COPYRIGHT("symbol_copyright"),
	SYMBOL_DOLLAR("symbol_dollar"),
	SYMBOL_DOLLAR_EURO("symbol_dollar_euro"),
	SYMBOL_EURO("symbol_euro"),
	SYMBOL_FEMALE("symbol_female"),
	SYMBOL_HASH("symbol_hash"),
	SYMBOL_MALE("symbol_male"),
	SYMBOL_PARAGRAPH("symbol_paragraph"),
	SYMBOL_PERCENT("symbol_percent"),
	SYMBOL_POUND("symbol_pound"),
	SYMBOL_Q("symbol_q"),
	SYMBOL_QUESTIONMARK("symbol_questionmark"),
	SYMBOL_SUM("symbol_sum"),
	SYMBOL_YEN("symbol_yen"),
	SYMBOL_YUAN("symbol_yuan"),
	SYNAGOGUE("synagogue"),
	SYSTEM("system"),
	TAB_PANE("tab_pane"),
	TABLE("table"),
	TABLE_SELECTION_ALL("table_selection_all"),
	TABLE_SELECTION_BLOCK("table_selection_block"),
	TABLE_SELECTION_CELL("table_selection_cell"),
	TABLE_SELECTION_COLUMN("table_selection_column"),
	TABLE_SELECTION_RANGE("table_selection_range"),
	TABLE_SELECTION_ROW("table_selection_row"),
	TABLE_TENNIS_RACKET("table_tennis_racket"),
	TABLES("tables"),
	TABLET_COMPUTER("tablet_computer"),
	TABLET_COMPUTER_TOUCH("tablet_computer_touch"),
	TAG("tag"),
	TAGS("tags"),
	TANK("tank"),
	TANK_TRUCK("tank_truck"),
	TAPE_MEASURE("tape_measure"),
	TAPE_MEASURE2("tape_measure2"),
	TARGET("target"),
	TAXI("taxi"),
	TEA_BAG("tea_bag"),
	TEACHER("teacher"),
	TEDDY_BEAR("teddy_bear"),
	TELEPHONE("telephone"),
	TELEPHONE2("telephone2"),
	TELEPHONE_BOX("telephone_box"),
	TELESCOPE("telescope"),
	TEMPLE("temple"),
	TENNIS_BALL("tennis_ball"),
	TENNIS_RACKET("tennis_racket"),
	TENT("tent"),
	TERRORIST("terrorist"),
	TEST_CARD("test_card"),
	TEXT("text"),
	TEXT_ALIGN_CENTER("text_align_center"),
	TEXT_ALIGN_JUSTIFIED("text_align_justified"),
	TEXT_ALIGN_LEFT("text_align_left"),
	TEXT_ALIGN_RIGHT("text_align_right"),
	TEXT_BINARY("text_binary"),
	TEXT_BRAILLE("text_braille"),
	TEXT_FIELD("text_field"),
	TEXT_SPEAKER("text_speaker"),
	TEXT_TREE("text_tree"),
	THERMOMETER("thermometer"),
	THERMOMETER2("thermometer2"),
	THOUGHT("thought"),
	THREAD("thread"),
	TICKET("ticket"),
	TIMER("timer"),
	TOASTER("toaster"),
	TOBACCO_PIPE("tobacco_pipe"),
	TOILET("toilet"),
	TOILET_PAPER("toilet_paper"),
	TOOL_TIP("tool_tip"),
	TOOLBOX("toolbox"),
	TOOLS("tools"),
	TOOTH("tooth"),
	TOOTH_CARIOUS("tooth_carious"),
	TORII("torii"),
	TORPEDO("torpedo"),
	TOUCH("touch"),
	TOWER_CRANE("tower_crane"),
	TRACTOR("tractor"),
	TRAFFICLIGHT_GREEN("trafficlight_green"),
	TRAFFICLIGHT_OFF("trafficlight_off"),
	TRAFFICLIGHT_ON("trafficlight_on"),
	TRAFFICLIGHT_RED("trafficlight_red"),
	TRAFFICLIGHT_RED_YELLOW("trafficlight_red_yellow"),
	TRAFFICLIGHT_YELLOW("trafficlight_yellow"),
	TRAM("tram"),
	TREE("tree"),
	TROJAN_HORSE("trojan_horse"),
	TROPHY("trophy"),
	TRUCK("truck"),
	TRUCK2("truck2"),
	TRUCK_CONTAINER("truck_container"),
	TRUCK_TRAILER("truck_trailer"),
	TV("tv"),
	TWEEZERS("tweezers"),
	TYPEWRITER("typewriter"),
	UFO("ufo"),
	UMBRELLA_CLOSED("umbrella_closed"),
	UMBRELLA_OPEN("umbrella_open"),
	UNDO("undo"),
	UNINSTALL("uninstall"),
	UNIVERSITY("university"),
	UPLOAD("upload"),
	USER("user"),
	USER_EARTH("user_earth"),
	USER_GLASSES("user_glasses"),
	USER_HEADPHONES("user_headphones"),
	USER_HEADSET("user_headset"),
	USER_MESSAGE("user_message"),
	USER_MOBILE_PHONE("user_mobile_phone"),
	USER_MONITOR("user_monitor"),
	USER_SMARTPHONE("user_smartphone"),
	USER_TELEPHONE("user_telephone"),
	USERS("users"),
	USERS2("users2"),
	USERS3("users3"),
	USERS4("users4"),
	USERS5("users5"),
	USERS_CROWD("users_crowd"),
	USERS_FAMILY("users_family"),
	USERS_MEETING("users_meeting"),
	USERS_RELATION("users_relation"),
	USERS_RELATION2("users_relation2"),
	UTILITY_KNIFE("utility_knife"),
	VACUUM_CLEANER("vacuum_cleaner"),
	VAN("van"),
	VECTOR_CIRCLE("vector_circle"),
	VECTOR_CURVE_CUBIC("vector_curve_cubic"),
	VECTOR_CURVE_QUADRATIC("vector_curve_quadratic"),
	VECTOR_ELLIPSE("vector_ellipse"),
	VECTOR_LINE("vector_line"),
	VECTOR_SQUARE("vector_square"),
	VECTOR_TRIANGLE("vector_triangle"),
	VENDING_MACHINE("vending_machine"),
	VIDEO_CAMERA("video_camera"),
	VIDEO_CHAT("video_chat"),
	VIDEO_CHAT2("video_chat2"),
	VIDEOTAPE("videotape"),
	VIEW_1_1("view_1_1"),
	VIOLIN("violin"),
	VIRUS("virus"),
	VOICE_RECORDER("voice_recorder"),
	VOODOO_DOLL("voodoo_doll"),
	WALKIE_TALKIE("walkie_talkie"),
	WALL_BARBED_WIRE("wall_barbed_wire"),
	WALLET("wallet"),
	WALLET_EMPTY("wallet_empty"),
	WAREHOUSE("warehouse"),
	WASHING_POWDER("washing_powder"),
	WATER("water"),
	WATER_FISH("water_fish"),
	WATER_TAP("water_tap"),
	WATERING_CAN("watering_can"),
	WATERING_CAN_HALF("watering_can_half"),
	WAX_SEAL("wax_seal"),
	WAX_SEAL_BROKEN("wax_seal_broken"),
	WEB("web"),
	WEBCAM("webcam"),
	WEDDING_RINGS("wedding_rings"),
	WEIGHT("weight"),
	WEIGHT2("weight2"),
	WHEAT("wheat"),
	WHEEL("wheel"),
	WHEEL_LOADER("wheel_loader"),
	WHEELBARROW("wheelbarrow"),
	WHEELBARROW_FULL("wheelbarrow_full"),
	WHEELCHAIR("wheelchair"),
	WHISTLE("whistle"),
	WHISTLE_NOISE("whistle_noise"),
	WIND_ENGINE("wind_engine"),
	WIND_ENGINE_OFFSHORE("wind_engine_offshore"),
	WIND_ENGINES("wind_engines"),
	WINDMILL("windmill"),
	WINDOW("window"),
	WINDOW_CD("window_cd"),
	WINDOW_CLOSE("window_close"),
	WINDOW_DIALOG("window_dialog"),
	WINDOW_EARTH("window_earth"),
	WINDOW_ENVIRONMENT("window_environment"),
	WINDOW_EQUALIZER("window_equalizer"),
	WINDOW_EXPLORER("window_explorer"),
	WINDOW_FONT("window_font"),
	WINDOW_GEAR("window_gear"),
	WINDOW_HEIGHT("window_height"),
	WINDOW_INFORMATION("window_information"),
	WINDOW_KEY("window_key"),
	WINDOW_LOGON("window_logon"),
	WINDOW_NETWORK("window_network"),
	WINDOW_OSCILLOGRAPH("window_oscillograph"),
	WINDOW_SIDEBAR("window_sidebar"),
	WINDOW_SIZE("window_size"),
	WINDOW_SPLIT_HOR("window_split_hor"),
	WINDOW_SPLIT_VER("window_split_ver"),
	WINDOW_STAR("window_star"),
	WINDOW_TEST_CARD("window_test_card"),
	WINDOW_TIME("window_time"),
	WINDOW_TOUCH("window_touch"),
	WINDOW_WARNING("window_warning"),
	WINDOW_WIDTH("window_width"),
	WINDOWS("windows"),
	WINDOWS_CLOSE("windows_close"),
	WINDSOCK("windsock"),
	WINDUP_KEY("windup_key"),
	WINE("wine"),
	WINE_BOTTLE("wine_bottle"),
	WINE_GLASS("wine_glass"),
	WLAN_ANTENNA("wlan_antenna"),
	WLAN_ROUTER("wlan_router"),
	WOMAN("woman"),
	WOMAN2("woman2"),
	WOMAN3("woman3"),
	WOODEN_PALLET("wooden_pallet"),
	WOODEN_PALLET_BOX("wooden_pallet_box"),
	WORKER("worker"),
	WORKER2("worker2"),
	WORKPLACE("workplace"),
	WORKSTATION("workstation"),
	WORKSTATION_NETWORK("workstation_network"),
	WORM("worm"),
	WRENCH("wrench"),
	WRISTWATCH("wristwatch"),
	X_RAY("x-ray"),
	YINYANG("yinyang"),
	ZOOM_IN("zoom_in"),
	ZOOM_OUT("zoom_out"),


	FLAG_AFGHANISTAN("flag_afghanistan"),
	FLAG_ALBANIA("flag_albania"),
	FLAG_ALGERIA("flag_algeria"),
	FLAG_AMERICAN_SAMOA("flag_american_samoa"),
	FLAG_ANDORRA("flag_andorra"),
	FLAG_ANGOLA("flag_angola"),
	FLAG_ANGUILLA("flag_anguilla"),
	FLAG_ANTIGUA_AND_BARBUDA("flag_antigua_and_barbuda"),
	FLAG_ARGENTINA("flag_argentina"),
	FLAG_ARMENIA("flag_armenia"),
	FLAG_ARUBA("flag_aruba"),
	FLAG_AUSTRALIA("flag_australia"),
	FLAG_AUSTRIA("flag_austria"),
	FLAG_AZERBAIJAN("flag_azerbaijan"),
	FLAG_BAHAMAS("flag_bahamas"),
	FLAG_BAHRAIN("flag_bahrain"),
	FLAG_BANGLADESH("flag_bangladesh"),
	FLAG_BARBADOS("flag_barbados"),
	FLAG_BELARUS("flag_belarus"),
	FLAG_BELGIUM("flag_belgium"),
	FLAG_BELIZE("flag_belize"),
	FLAG_BENIN("flag_benin"),
	FLAG_BERMUDA("flag_bermuda"),
	FLAG_BHUTAN("flag_bhutan"),
	FLAG_BOLIVIA("flag_bolivia"),
	FLAG_BOSNIA_AND_HERZEGOVINA("flag_bosnia_and_herzegovina"),
	FLAG_BOTSWANA("flag_botswana"),
	FLAG_BRAZIL("flag_brazil"),
	FLAG_BRITISH_INDIAN_OCEAN_TERRITORY("flag_british_indian_ocean_territory"),
	FLAG_BRITISH_VIRGIN_ISLANDS("flag_british_virgin_islands"),
	FLAG_BRUNEI("flag_brunei"),
	FLAG_BULGARIA("flag_bulgaria"),
	FLAG_BURKINA_FASO("flag_burkina_faso"),
	FLAG_BURMA("flag_burma"),
	FLAG_BURUNDI("flag_burundi"),
	FLAG_CAMBODIA("flag_cambodia"),
	FLAG_CAMEROON("flag_cameroon"),
	FLAG_CANADA("flag_canada"),
	FLAG_CAPE_VERDE("flag_cape_verde"),
	FLAG_CAYMAN_ISLANDS("flag_cayman_islands"),
	FLAG_CENTRAL_AFRICAN_REPUBLIC("flag_central_african_republic"),
	FLAG_CHAD("flag_chad"),
	FLAG_CHECKERED("flag_checkered"),
	FLAG_CHILE("flag_chile"),
	FLAG_CHINA("flag_china"),
	FLAG_COLOMBIA("flag_colombia"),
	FLAG_COMOROS("flag_comoros"),
	FLAG_CONGO_DEMOCRATIC_REPUBLIC("flag_congo_democratic_republic"),
	FLAG_CONGO_REPUBLIC("flag_congo_republic"),
	FLAG_COOK_ISLANDS("flag_cook_islands"),
	FLAG_COSTA_RICA("flag_costa_rica"),
	FLAG_COTE_DIVOIRE("flag_cote_divoire"),
	FLAG_CROATIA("flag_croatia"),
	FLAG_CUBA("flag_cuba"),
	FLAG_CYPRUS("flag_cyprus"),
	FLAG_CZECH_REPUBLIC("flag_czech_republic"),
	FLAG_DENMARK("flag_denmark"),
	FLAG_DJIBOUTI("flag_djibouti"),
	FLAG_DOMINICA("flag_dominica"),
	FLAG_DOMINICAN_REPUBLIC("flag_dominican_republic"),
	FLAG_EAST_TIMOR("flag_east_timor"),
	FLAG_ECUADOR("flag_ecuador"),
	FLAG_EGYPT("flag_egypt"),
	FLAG_EL_SALVADOR("flag_el_salvador"),
	FLAG_ENGLAND("flag_england"),
	FLAG_EQUATORIAL_GUINEA("flag_equatorial_guinea"),
	FLAG_ERITREA("flag_eritrea"),
	FLAG_ESTONIA("flag_estonia"),
	FLAG_ETHIOPIA("flag_ethiopia"),
	FLAG_EU("flag_eu"),
	FLAG_FAEROE_ISLANDS("flag_faeroe_islands"),
	FLAG_FALKLAND_ISLANDS("flag_falkland_islands"),
	FLAG_FIJI("flag_fiji"),
	FLAG_FINLAND("flag_finland"),
	FLAG_FRANCE("flag_france"),
	FLAG_FRENCH_POLYNESIA("flag_french_polynesia"),
	FLAG_GABON("flag_gabon"),
	FLAG_GAMBIA("flag_gambia"),
	FLAG_GENERIC("flag_generic"),
	FLAG_GEORGIA("flag_georgia"),
	FLAG_GERMANY("flag_germany"),
	FLAG_GHANA("flag_ghana"),
	FLAG_GIBRALTAR("flag_gibraltar"),
	FLAG_GREECE("flag_greece"),
	FLAG_GREENLAND("flag_greenland"),
	FLAG_GRENADA("flag_grenada"),
	FLAG_GUAM("flag_guam"),
	FLAG_GUATEMALA("flag_guatemala"),
	FLAG_GUERNSEY("flag_guernsey"),
	FLAG_GUINEA("flag_guinea"),
	FLAG_GUINEA_BISSAU("flag_guinea_bissau"),
	FLAG_GUYANA("flag_guyana"),
	FLAG_HAITI("flag_haiti"),
	FLAG_HONDURAS("flag_honduras"),
	FLAG_HONG_KONG("flag_hong_kong"),
	FLAG_HUNGARY("flag_hungary"),
	FLAG_ICELAND("flag_iceland"),
	FLAG_INDIA("flag_india"),
	FLAG_INDONESIA("flag_indonesia"),
	FLAG_IRAN("flag_iran"),
	FLAG_IRAQ("flag_iraq"),
	FLAG_IRELAND("flag_ireland"),
	FLAG_ISLE_OF_MAN("flag_isle_of_man"),
	FLAG_ISRAEL("flag_israel"),
	FLAG_ITALY("flag_italy"),
	FLAG_JAMAICA("flag_jamaica"),
	FLAG_JAPAN("flag_japan"),
	FLAG_JERSEY("flag_jersey"),
	FLAG_JORDAN("flag_jordan"),
	FLAG_KAZAKHSTAN("flag_kazakhstan"),
	FLAG_KENYA("flag_kenya"),
	FLAG_KIRIBATI("flag_kiribati"),
	FLAG_KUWAIT("flag_kuwait"),
	FLAG_KYRGYZSTAN("flag_kyrgyzstan"),
	FLAG_LAOS("flag_laos"),
	FLAG_LATVIA("flag_latvia"),
	FLAG_LEBANON("flag_lebanon"),
	FLAG_LESOTHO("flag_lesotho"),
	FLAG_LIBERIA("flag_liberia"),
	FLAG_LIBYA("flag_libya"),
	FLAG_LIECHTENSTEIN("flag_liechtenstein"),
	FLAG_LITHUANIA("flag_lithuania"),
	FLAG_LUXEMBOURG("flag_luxembourg"),
	FLAG_MACAU("flag_macau"),
	FLAG_MACEDONIA("flag_macedonia"),
	FLAG_MADAGASCAR("flag_madagascar"),
	FLAG_MALAWI("flag_malawi"),
	FLAG_MALAYSIA("flag_malaysia"),
	FLAG_MALDIVES("flag_maldives"),
	FLAG_MALI("flag_mali"),
	FLAG_MALTA("flag_malta"),
	FLAG_MARSHALL_ISLANDS("flag_marshall_islands"),
	FLAG_MARTINIQUE("flag_martinique"),
	FLAG_MAURITANIA("flag_mauritania"),
	FLAG_MAURITIUS("flag_mauritius"),
	FLAG_MEXICO("flag_mexico"),
	FLAG_MICRONESIA("flag_micronesia"),
	FLAG_MOLDOVA("flag_moldova"),
	FLAG_MONACO("flag_monaco"),
	FLAG_MONGOLIA("flag_mongolia"),
	FLAG_MONTENEGRO("flag_montenegro"),
	FLAG_MONTSERRAT("flag_montserrat"),
	FLAG_MOROCCO("flag_morocco"),
	FLAG_MOZAMBIQUE("flag_mozambique"),
	FLAG_NAMIBIA("flag_namibia"),
	FLAG_NAURU("flag_nauru"),
	FLAG_NEPAL("flag_nepal"),
	FLAG_NETHERLANDS("flag_netherlands"),
	FLAG_NETHERLANDS_ANTILLES("flag_netherlands_antilles"),
	FLAG_NEW_ZEALAND("flag_new_zealand"),
	FLAG_NICARAGUA("flag_nicaragua"),
	FLAG_NIGER("flag_niger"),
	FLAG_NIGERIA("flag_nigeria"),
	FLAG_NIUE("flag_niue"),
	FLAG_NORFOLK_ISLAND("flag_norfolk_island"),
	FLAG_NORTH_KOREA("flag_north_korea"),
	FLAG_NORTHERN_MARIANA_ISLANDS("flag_northern_mariana_islands"),
	FLAG_NORWAY("flag_norway"),
	FLAG_OMAN("flag_oman"),
	FLAG_PAKISTAN("flag_pakistan"),
	FLAG_PALAU("flag_palau"),
	FLAG_PANAMA("flag_panama"),
	FLAG_PAPUA_NEW_GUINEA("flag_papua_new_guinea"),
	FLAG_PARAGUAY("flag_paraguay"),
	FLAG_PERU("flag_peru"),
	FLAG_PHILIPPINES("flag_philippines"),
	FLAG_PIRATE("flag_pirate"),
	FLAG_PITCAIRN_ISLANDS("flag_pitcairn_islands"),
	FLAG_POLAND("flag_poland"),
	FLAG_PORTUGAL("flag_portugal"),
	FLAG_PUERTO_RICO("flag_puerto_rico"),
	FLAG_QATAR("flag_qatar"),
	FLAG_RAINBOW("flag_rainbow"),
	FLAG_ROMANIA("flag_romania"),
	FLAG_RUSSIA("flag_russia"),
	FLAG_RWANDA("flag_rwanda"),
	FLAG_SAINT_HELENA("flag_saint_helena"),
	FLAG_SAINT_KITTS_AND_NEVIS("flag_saint_kitts_and_nevis"),
	FLAG_SAINT_LUCIA("flag_saint_lucia"),
	FLAG_SAINT_PIERRE_AND_MIQUELON("flag_saint_pierre_and_miquelon"),
	FLAG_SAINT_VINCENT_AND_THE_GRENADINES("flag_saint_vincent_and_the_grenadines"),
	FLAG_SAMOA("flag_samoa"),
	FLAG_SAN_MARINO("flag_san_marino"),
	FLAG_SAO_TOME_AND_PRINCIPE("flag_sao_tome_and_principe"),
	FLAG_SAUDI_ARABIA("flag_saudi_arabia"),
	FLAG_SCOTLAND("flag_scotland"),
	FLAG_SENEGAL("flag_senegal"),
	FLAG_SERBIA("flag_serbia"),
	FLAG_SEYCHELLES("flag_seychelles"),
	FLAG_SIERRA_LEONE("flag_sierra_leone"),
	FLAG_SINGAPORE("flag_singapore"),
	FLAG_SLOVAKIA("flag_slovakia"),
	FLAG_SLOVENIA("flag_slovenia"),
	FLAG_SOLOMON_ISLANDS("flag_solomon_islands"),
	FLAG_SOMALIA("flag_somalia"),
	FLAG_SOUTH_AFRICA("flag_south_africa"),
	FLAG_SOUTH_GEORGIA("flag_south_georgia"),
	FLAG_SOUTH_KOREA("flag_south_korea"),
	FLAG_SPAIN("flag_spain"),
	FLAG_SRI_LANKA("flag_sri_lanka"),
	FLAG_SUDAN("flag_sudan"),
	FLAG_SURINAME("flag_suriname"),
	FLAG_SWAZILAND("flag_swaziland"),
	FLAG_SWEDEN("flag_sweden"),
	FLAG_SWITZERLAND("flag_switzerland"),
	FLAG_SYRIA("flag_syria"),
	FLAG_TAIWAN("flag_taiwan"),
	FLAG_TAJIKISTAN("flag_tajikistan"),
	FLAG_TANZANIA("flag_tanzania"),
	FLAG_THAILAND("flag_thailand"),
	FLAG_TIBET("flag_tibet"),
	FLAG_TOGO("flag_togo"),
	FLAG_TONGA("flag_tonga"),
	FLAG_TRINIDAD_AND_TOBAGO("flag_trinidad_and_tobago"),
	FLAG_TUNISIA("flag_tunisia"),
	FLAG_TURKEY("flag_turkey"),
	FLAG_TURKMENISTAN("flag_turkmenistan"),
	FLAG_TURKS_AND_CAICOS_ISLANDS("flag_turks_and_caicos_islands"),
	FLAG_TUVALU("flag_tuvalu"),
	FLAG_UGANDA("flag_uganda"),
	FLAG_UKRAINE("flag_ukraine"),
	FLAG_UNITED_ARAB_EMIRATES("flag_united_arab_emirates"),
	FLAG_UNITED_KINGDOM("flag_united_kingdom"),
	FLAG_URUGUAY("flag_uruguay"),
	FLAG_USA("flag_usa"),
	FLAG_UZBEKISTAN("flag_uzbekistan"),
	FLAG_VANUATU("flag_vanuatu"),
	FLAG_VATICAN_CITY("flag_vatican_city"),
	FLAG_VENEZUELA("flag_venezuela"),
	FLAG_VIETNAM("flag_vietnam"),
	FLAG_VIRGIN_ISLANDS("flag_virgin_islands"),
	FLAG_WALES("flag_wales"),
	FLAG_WALLIS_AND_FUTUNA("flag_wallis_and_futuna"),
	FLAG_WHITE("flag_white"),
	FLAG_YEMEN("flag_yemen"),
	FLAG_ZAMBIA("flag_zambia"),
	FLAG_ZIMBABWE("flag_zimbabwe"),

	;

	public static final String LIBRARY_ID = "standard";

	private String name;

	Icons(String name) {
		this.name = name;
	}

	@Override
	public String getIconName() {
		return name;
	}

	@Override
	public String getIconLibraryId() {
		return LIBRARY_ID;
	}

	public static Icon getIconForName(String name) {
		return Arrays.stream(values())
				.filter(icon -> icon.getIconName().equals(name))
				.findAny()
				.orElse(null);
	}

	public static Icon getIconForCountryIsoCode(String countryIso) {
		if (countryIso == null || countryIso.isEmpty()) {
			return null;
		}
		countryIso = countryIso.toUpperCase();
		switch (countryIso) {
			case "AW": return Icons.FLAG_ARUBA;
			case "AF": return Icons.FLAG_AFGHANISTAN;
			case "AO": return Icons.FLAG_ANGOLA;
			case "AI": return Icons.FLAG_ANGUILLA;
			case "AX": return Icons.EARTH_LOCATION;
			case "AL": return Icons.FLAG_ALBANIA;
			case "AD": return Icons.FLAG_ANDORRA;
			case "AE": return Icons.FLAG_UNITED_ARAB_EMIRATES;
			case "AR": return Icons.FLAG_ARGENTINA;
			case "AM": return Icons.FLAG_ARMENIA;
			case "AS": return Icons.FLAG_AMERICAN_SAMOA;
			case "AQ": return Icons.EARTH_LOCATION;
			case "TF": return Icons.EARTH_LOCATION;
			case "AG": return Icons.FLAG_ANTIGUA_AND_BARBUDA;
			case "AU": return Icons.FLAG_AUSTRALIA;
			case "AT": return Icons.FLAG_AUSTRIA;
			case "AZ": return Icons.FLAG_AZERBAIJAN;
			case "BI": return Icons.FLAG_BURUNDI;
			case "BE": return Icons.FLAG_BELGIUM;
			case "BJ": return Icons.FLAG_BENIN;
			case "BQ": return Icons.EARTH_LOCATION;
			case "BF": return Icons.FLAG_BURKINA_FASO;
			case "BD": return Icons.FLAG_BANGLADESH;
			case "BG": return Icons.FLAG_BULGARIA;
			case "BH": return Icons.FLAG_BAHRAIN;
			case "BS": return Icons.FLAG_BAHAMAS;
			case "BA": return Icons.FLAG_BOSNIA_AND_HERZEGOVINA;
			case "BL": return Icons.EARTH_LOCATION;
			case "BY": return Icons.FLAG_BELARUS;
			case "BZ": return Icons.FLAG_BELIZE;
			case "BM": return Icons.FLAG_BERMUDA;
			case "BO": return Icons.FLAG_BOLIVIA;
			case "BR": return Icons.FLAG_BRAZIL;
			case "BB": return Icons.FLAG_BARBADOS;
			case "BN": return Icons.FLAG_BRUNEI;
			case "BT": return Icons.FLAG_BHUTAN;
			case "BV": return Icons.EARTH_LOCATION;
			case "BW": return Icons.FLAG_BOTSWANA;
			case "CF": return Icons.FLAG_CENTRAL_AFRICAN_REPUBLIC;
			case "CA": return Icons.FLAG_CANADA;
			case "CC": return Icons.EARTH_LOCATION;
			case "CH": return Icons.FLAG_SWITZERLAND;
			case "CL": return Icons.FLAG_CHILE;
			case "CN": return Icons.FLAG_CHINA;
			case "CI": return Icons.FLAG_COTE_DIVOIRE;
			case "CM": return Icons.FLAG_CAMEROON;
			case "CD": return Icons.FLAG_CONGO_DEMOCRATIC_REPUBLIC;
			case "CG": return Icons.FLAG_CONGO_REPUBLIC;
			case "CK": return Icons.FLAG_COOK_ISLANDS;
			case "CO": return Icons.FLAG_COLOMBIA;
			case "KM": return Icons.FLAG_COMOROS;
			case "CV": return Icons.FLAG_CAPE_VERDE;
			case "CR": return Icons.FLAG_COSTA_RICA;
			case "CU": return Icons.FLAG_CUBA;
			case "CW": return Icons.EARTH_LOCATION;
			case "CX": return Icons.EARTH_LOCATION;
			case "KY": return Icons.FLAG_CAYMAN_ISLANDS;
			case "CY": return Icons.FLAG_CYPRUS;
			case "CZ": return Icons.FLAG_CZECH_REPUBLIC;
			case "DE": return Icons.FLAG_GERMANY;
			case "DJ": return Icons.FLAG_DJIBOUTI;
			case "DM": return Icons.FLAG_DOMINICA;
			case "DK": return Icons.FLAG_DENMARK;
			case "DO": return Icons.FLAG_DOMINICAN_REPUBLIC;
			case "DZ": return Icons.FLAG_ALGERIA;
			case "EC": return Icons.FLAG_ECUADOR;
			case "EG": return Icons.FLAG_EGYPT;
			case "ER": return Icons.FLAG_ERITREA;
			case "EH": return Icons.EARTH_LOCATION;
			case "ES": return Icons.FLAG_SPAIN;
			case "EE": return Icons.FLAG_ESTONIA;
			case "ET": return Icons.FLAG_ETHIOPIA;
			case "FI": return Icons.FLAG_FINLAND;
			case "FJ": return Icons.FLAG_FIJI;
			case "FK": return Icons.FLAG_FALKLAND_ISLANDS;
			case "FR": return Icons.FLAG_FRANCE;
			case "FO": return Icons.FLAG_FAEROE_ISLANDS;
			case "FM": return Icons.FLAG_MICRONESIA;
			case "GA": return Icons.FLAG_GABON;
			case "GB": return Icons.FLAG_UNITED_KINGDOM;
			case "GE": return Icons.FLAG_GEORGIA;
			case "GG": return Icons.FLAG_GUERNSEY;
			case "GH": return Icons.FLAG_GHANA;
			case "GI": return Icons.FLAG_GIBRALTAR;
			case "GN": return Icons.FLAG_GUINEA;
			case "GP": return Icons.EARTH_LOCATION;
			case "GM": return Icons.FLAG_GAMBIA;
			case "GW": return Icons.FLAG_GUINEA_BISSAU;
			case "GQ": return Icons.FLAG_EQUATORIAL_GUINEA;
			case "GR": return Icons.FLAG_GREECE;
			case "GD": return Icons.FLAG_GRENADA;
			case "GL": return Icons.FLAG_GREENLAND;
			case "GT": return Icons.FLAG_GUATEMALA;
			case "GF": return Icons.EARTH_LOCATION;
			case "GU": return Icons.FLAG_GUAM;
			case "GY": return Icons.FLAG_GUYANA;
			case "HK": return Icons.FLAG_HONG_KONG;
			case "HM": return Icons.EARTH_LOCATION;
			case "HN": return Icons.FLAG_HONDURAS;
			case "HR": return Icons.FLAG_CROATIA;
			case "HT": return Icons.FLAG_HAITI;
			case "HU": return Icons.FLAG_HUNGARY;
			case "ID": return Icons.FLAG_INDONESIA;
			case "IM": return Icons.FLAG_ISLE_OF_MAN;
			case "IN": return Icons.FLAG_INDIA;
			case "IO": return Icons.FLAG_BRITISH_INDIAN_OCEAN_TERRITORY;
			case "IE": return Icons.FLAG_IRELAND;
			case "IR": return Icons.FLAG_IRAN;
			case "IQ": return Icons.FLAG_IRAQ;
			case "IS": return Icons.FLAG_ICELAND;
			case "IL": return Icons.FLAG_ISRAEL;
			case "IT": return Icons.FLAG_ITALY;
			case "JM": return Icons.FLAG_JAMAICA;
			case "JE": return Icons.FLAG_JERSEY;
			case "JO": return Icons.FLAG_JORDAN;
			case "JP": return Icons.FLAG_JAPAN;
			case "KZ": return Icons.FLAG_KAZAKHSTAN;
			case "KE": return Icons.FLAG_KENYA;
			case "KG": return Icons.FLAG_KYRGYZSTAN;
			case "KH": return Icons.FLAG_CAMBODIA;
			case "KI": return Icons.FLAG_KIRIBATI;
			case "KN": return Icons.FLAG_SAINT_KITTS_AND_NEVIS;
			case "KW": return Icons.FLAG_KUWAIT;
			case "LA": return Icons.FLAG_LAOS;
			case "LB": return Icons.FLAG_LEBANON;
			case "LR": return Icons.FLAG_LIBERIA;
			case "LY": return Icons.FLAG_LIBYA;
			case "LC": return Icons.FLAG_SAINT_LUCIA;
			case "LI": return Icons.FLAG_LIECHTENSTEIN;
			case "LK": return Icons.FLAG_SRI_LANKA;
			case "LS": return Icons.FLAG_LESOTHO;
			case "LT": return Icons.FLAG_LITHUANIA;
			case "LU": return Icons.FLAG_LUXEMBOURG;
			case "LV": return Icons.FLAG_LATVIA;
			case "MO": return Icons.FLAG_MACAU;
			case "MF": return Icons.EARTH_LOCATION;
			case "MA": return Icons.FLAG_MOROCCO;
			case "MC": return Icons.FLAG_MONACO;
			case "MD": return Icons.FLAG_MOLDOVA;
			case "MG": return Icons.FLAG_MADAGASCAR;
			case "MV": return Icons.FLAG_MALDIVES;
			case "MX": return Icons.FLAG_MEXICO;
			case "MH": return Icons.FLAG_MARSHALL_ISLANDS;
			case "MK": return Icons.FLAG_MACEDONIA;
			case "ML": return Icons.FLAG_MALI;
			case "MT": return Icons.FLAG_MALTA;
			case "MM": return Icons.FLAG_BURMA;
			case "ME": return Icons.FLAG_MONTENEGRO;
			case "MN": return Icons.FLAG_MONGOLIA;
			case "MP": return Icons.FLAG_NORTHERN_MARIANA_ISLANDS;
			case "MZ": return Icons.FLAG_MOZAMBIQUE;
			case "MR": return Icons.FLAG_MAURITANIA;
			case "MS": return Icons.FLAG_MONTSERRAT;
			case "MQ": return Icons.FLAG_MARTINIQUE;
			case "MU": return Icons.FLAG_MAURITIUS;
			case "MW": return Icons.FLAG_MALAWI;
			case "MY": return Icons.FLAG_MALAYSIA;
			case "YT": return Icons.EARTH_LOCATION;
			case "NA": return Icons.FLAG_NAMIBIA;
			case "NC": return Icons.EARTH_LOCATION;
			case "NE": return Icons.FLAG_NIGER;
			case "NF": return Icons.FLAG_NORFOLK_ISLAND;
			case "NG": return Icons.FLAG_NIGERIA;
			case "NI": return Icons.FLAG_NICARAGUA;
			case "NU": return Icons.FLAG_NIUE;
			case "NL": return Icons.FLAG_NETHERLANDS;
			case "NO": return Icons.FLAG_NORWAY;
			case "NP": return Icons.FLAG_NEPAL;
			case "NR": return Icons.FLAG_NAURU;
			case "NZ": return Icons.FLAG_NEW_ZEALAND;
			case "OM": return Icons.FLAG_OMAN;
			case "PK": return Icons.FLAG_PAKISTAN;
			case "PA": return Icons.FLAG_PANAMA;
			case "PN": return Icons.FLAG_PITCAIRN_ISLANDS;
			case "PE": return Icons.FLAG_PERU;
			case "PH": return Icons.FLAG_PHILIPPINES;
			case "PW": return Icons.FLAG_PALAU;
			case "PG": return Icons.FLAG_PAPUA_NEW_GUINEA;
			case "PL": return Icons.FLAG_POLAND;
			case "PR": return Icons.FLAG_PUERTO_RICO;
			case "KP": return Icons.FLAG_NORTH_KOREA;
			case "KR": return Icons.FLAG_SOUTH_KOREA;
			case "PT": return Icons.FLAG_PORTUGAL;
			case "PY": return Icons.FLAG_PARAGUAY;
			case "PS": return Icons.EARTH_LOCATION;
			case "PF": return Icons.FLAG_FRENCH_POLYNESIA;
			case "QA": return Icons.FLAG_QATAR;
			case "RE": return Icons.EARTH_LOCATION;
			case "RO": return Icons.FLAG_ROMANIA;
			case "RU": return Icons.FLAG_RUSSIA;
			case "RW": return Icons.FLAG_RWANDA;
			case "SA": return Icons.FLAG_SAUDI_ARABIA;
			case "SD": return Icons.FLAG_SUDAN;
			case "SN": return Icons.FLAG_SENEGAL;
			case "SG": return Icons.FLAG_SINGAPORE;
			case "GS": return Icons.EARTH_LOCATION;
			case "SH": return Icons.FLAG_SAINT_HELENA;
			case "SJ": return Icons.EARTH_LOCATION;
			case "SB": return Icons.FLAG_SOLOMON_ISLANDS;
			case "SL": return Icons.FLAG_SIERRA_LEONE;
			case "SV": return Icons.FLAG_EL_SALVADOR;
			case "SM": return Icons.FLAG_SAN_MARINO;
			case "SX": return Icons.EARTH_LOCATION;
			case "SO": return Icons.FLAG_SOMALIA;
			case "PM": return Icons.FLAG_SAINT_PIERRE_AND_MIQUELON;
			case "RS": return Icons.FLAG_SERBIA;
			case "SS": return Icons.EARTH_LOCATION;
			case "ST": return Icons.FLAG_SAO_TOME_AND_PRINCIPE;
			case "SR": return Icons.FLAG_SURINAME;
			case "SK": return Icons.FLAG_SLOVAKIA;
			case "SI": return Icons.FLAG_SLOVENIA;
			case "SE": return Icons.FLAG_SWEDEN;
			case "SZ": return Icons.FLAG_SWAZILAND;
			case "SC": return Icons.FLAG_SEYCHELLES;
			case "SY": return Icons.FLAG_SYRIA;
			case "TC": return Icons.FLAG_TURKS_AND_CAICOS_ISLANDS;
			case "TD": return Icons.FLAG_CHAD;
			case "TG": return Icons.FLAG_TOGO;
			case "TH": return Icons.FLAG_THAILAND;
			case "TJ": return Icons.FLAG_TAJIKISTAN;
			case "TK": return Icons.EARTH_LOCATION;
			case "TM": return Icons.FLAG_TURKMENISTAN;
			case "TL": return Icons.FLAG_EAST_TIMOR;
			case "TO": return Icons.FLAG_TONGA;
			case "TT": return Icons.FLAG_TRINIDAD_AND_TOBAGO;
			case "TN": return Icons.FLAG_TUNISIA;
			case "TR": return Icons.FLAG_TURKEY;
			case "TV": return Icons.FLAG_TUVALU;
			case "TW": return Icons.FLAG_TAIWAN;
			case "TZ": return Icons.FLAG_TANZANIA;
			case "UG": return Icons.FLAG_UGANDA;
			case "UA": return Icons.FLAG_UKRAINE;
			case "UM": return Icons.EARTH_LOCATION;
			case "UY": return Icons.FLAG_URUGUAY;
			case "US": return Icons.FLAG_USA;
			case "UZ": return Icons.FLAG_UZBEKISTAN;
			case "VA": return Icons.FLAG_VATICAN_CITY;
			case "VC": return Icons.FLAG_SAINT_VINCENT_AND_THE_GRENADINES;
			case "VE": return Icons.FLAG_VENEZUELA;
			case "VG": return Icons.FLAG_BRITISH_VIRGIN_ISLANDS;
			case "VI": return Icons.EARTH_LOCATION;
			case "VN": return Icons.FLAG_VIETNAM;
			case "VU": return Icons.FLAG_VANUATU;
			case "WF": return Icons.EARTH_LOCATION;
			case "WS": return Icons.FLAG_SAMOA;
			case "YE": return Icons.FLAG_YEMEN;
			case "ZA": return Icons.FLAG_SOUTH_AFRICA;
			case "ZM": return Icons.FLAG_ZAMBIA;
			case "ZW": return Icons.FLAG_ZIMBABWE;
			case "AN": return Icons.FLAG_NETHERLANDS_ANTILLES;
			case "XK": return Icons.EARTH_LOCATION;
		}
		return null;
	}

	public static Icon getIconForLanguageIsoCode(String languageIsoCode) {
		if (languageIsoCode == null || languageIsoCode.isEmpty()) {
			return null;
		}
		languageIsoCode = languageIsoCode.toLowerCase();
		switch (languageIsoCode) {
			case "aa": return Icons.FLAG_ERITREA;
			case "ab": return Icons.SPEECH_BALLOON;
			case "af": return Icons.FLAG_SOUTH_AFRICA;
			case "am": return Icons.FLAG_ETHIOPIA;
			case "ar": return Icons.FLAG_SAUDI_ARABIA;
			case "as": return Icons.SPEECH_BALLOON;
			case "ay": return Icons.FLAG_BOLIVIA;
			case "az": return Icons.FLAG_AZERBAIJAN;
			case "ba": return Icons.FLAG_RUSSIA;
			case "be": return Icons.FLAG_BELARUS;
			case "bg": return Icons.FLAG_BULGARIA;
			case "bh": return Icons.FLAG_INDIA;
			case "bi": return Icons.SPEECH_BALLOON;
			case "bn": return Icons.FLAG_BANGLADESH;
			case "bo": return Icons.FLAG_TIBET;
			case "br": return Icons.FLAG_FRANCE;
			case "ca": return Icons.FLAG_SPAIN;
			case "co": return Icons.FLAG_ITALY;
			case "cs": return Icons.FLAG_CZECH_REPUBLIC;
			case "cy": return Icons.FLAG_UNITED_KINGDOM;
			case "da": return Icons.FLAG_DENMARK;
			case "de": return Icons.FLAG_GERMANY;
			case "dz": return Icons.FLAG_BHUTAN;
			case "el": return Icons.FLAG_GREECE;
			case "en": return Icons.FLAG_ENGLAND;
			case "eo": return Icons.SPEECH_BALLOON;
			case "es": return Icons.FLAG_SPAIN;
			case "et": return Icons.FLAG_ESTONIA;
			case "eu": return Icons.FLAG_SPAIN;
			case "fa": return Icons.FLAG_IRAN;
			case "fi": return Icons.FLAG_FINLAND;
			case "fj": return Icons.FLAG_FIJI;
			case "fo": return Icons.FLAG_DENMARK;
			case "fr": return Icons.FLAG_FRANCE;
			case "fy": return Icons.FLAG_GERMANY;
			case "ga": return Icons.FLAG_IRELAND;
			case "gd": return Icons.FLAG_SCOTLAND;
			case "gl": return Icons.FLAG_SPAIN;
			case "gn": return Icons.FLAG_PARAGUAY;
			case "gu": return Icons.FLAG_INDIA;
			case "ha": return Icons.FLAG_NIGER;
			case "he": return Icons.FLAG_ISRAEL;
			case "hi": return Icons.FLAG_INDIA;
			case "hr": return Icons.FLAG_CROATIA;
			case "hu": return Icons.FLAG_HUNGARY;
			case "hy": return Icons.FLAG_ARMENIA;
			case "ia": return Icons.SPEECH_BALLOON;
			case "id": return Icons.FLAG_INDONESIA;
			case "ie": return Icons.SPEECH_BALLOON;
			case "ik": return Icons.FLAG_USA;
			case "is": return Icons.FLAG_ICELAND;
			case "it": return Icons.FLAG_ITALY;
			case "iu": return Icons.FLAG_CANADA;
			case "ja": return Icons.FLAG_JAPAN;
			case "jv": return Icons.FLAG_INDONESIA;
			case "ka": return Icons.FLAG_GEORGIA;
			case "kk": return Icons.FLAG_KAZAKHSTAN;
			case "kl": return Icons.FLAG_GREENLAND;
			case "km": return Icons.FLAG_CAMBODIA;
			case "kn": return Icons.FLAG_INDIA;
			case "ko": return Icons.FLAG_SOUTH_KOREA;
			case "ks": return Icons.FLAG_INDIA;
			case "ku": return Icons.FLAG_TURKEY;
			case "ky": return Icons.FLAG_KYRGYZSTAN;
			case "la": return Icons.FLAG_ITALY;
			case "ln": return Icons.FLAG_CONGO_DEMOCRATIC_REPUBLIC;
			case "lo": return Icons.FLAG_LAOS;
			case "lt": return Icons.FLAG_LITHUANIA;
			case "lv": return Icons.FLAG_LATVIA;
			case "mg": return Icons.FLAG_MADAGASCAR;
			case "mi": return Icons.FLAG_NEW_ZEALAND;
			case "mk": return Icons.FLAG_MACEDONIA;
			case "ml": return Icons.FLAG_INDIA;
			case "mn": return Icons.FLAG_MONGOLIA;
			case "mo": return Icons.FLAG_MOLDOVA;
			case "mr": return Icons.FLAG_INDIA;
			case "ms": return Icons.FLAG_MALAYSIA;
			case "mt": return Icons.FLAG_MALTA;
			case "my": return Icons.FLAG_BURMA;
			case "na": return Icons.FLAG_NAURU;
			case "ne": return Icons.FLAG_NEPAL;
			case "nl": return Icons.FLAG_NETHERLANDS;
			case "no": return Icons.FLAG_NORWAY;
			case "oc": return Icons.FLAG_SPAIN;
			case "om": return Icons.FLAG_ETHIOPIA;
			case "or": return Icons.FLAG_INDIA;
			case "pa": return Icons.FLAG_INDIA;
			case "pl": return Icons.FLAG_POLAND;
			case "ps": return Icons.FLAG_AFGHANISTAN;
			case "pt": return Icons.FLAG_PORTUGAL;
			case "qu": return Icons.FLAG_PERU;
			case "rm": return Icons.FLAG_SWITZERLAND;
			case "rn": return Icons.SPEECH_BALLOON;
			case "ro": return Icons.FLAG_ROMANIA;
			case "ru": return Icons.FLAG_RUSSIA;
			case "rw": return Icons.SPEECH_BALLOON;
			case "sa": return Icons.SPEECH_BALLOON;
			case "sd": return Icons.SPEECH_BALLOON;
			case "sg": return Icons.SPEECH_BALLOON;
			case "sh": return Icons.FLAG_SERBIA;
			case "si": return Icons.SPEECH_BALLOON;
			case "sk": return Icons.FLAG_SLOVAKIA;
			case "sl": return Icons.FLAG_SLOVENIA;
			case "sm": return Icons.SPEECH_BALLOON;
			case "sn": return Icons.SPEECH_BALLOON;
			case "so": return Icons.FLAG_SOMALIA;
			case "sq": return Icons.FLAG_ALBANIA;
			case "sr": return Icons.FLAG_SERBIA;
			case "ss": return Icons.FLAG_SWAZILAND;
			case "st": return Icons.SPEECH_BALLOON;
			case "su": return Icons.SPEECH_BALLOON;
			case "sv": return Icons.FLAG_SWEDEN;
			case "sw": return Icons.FLAG_TANZANIA;
			case "ta": return Icons.SPEECH_BALLOON;
			case "te": return Icons.SPEECH_BALLOON;
			case "tg": return Icons.SPEECH_BALLOON;
			case "th": return Icons.FLAG_THAILAND;
			case "ti": return Icons.SPEECH_BALLOON;
			case "tk": return Icons.SPEECH_BALLOON;
			case "tl": return Icons.SPEECH_BALLOON;
			case "tn": return Icons.SPEECH_BALLOON;
			case "to": return Icons.SPEECH_BALLOON;
			case "tr": return Icons.FLAG_TURKEY;
			case "ts": return Icons.SPEECH_BALLOON;
			case "tt": return Icons.SPEECH_BALLOON;
			case "tw": return Icons.SPEECH_BALLOON;
			case "ug": return Icons.SPEECH_BALLOON;
			case "uk": return Icons.SPEECH_BALLOON;
			case "ur": return Icons.FLAG_UKRAINE;
			case "uz": return Icons.SPEECH_BALLOON;
			case "vi": return Icons.FLAG_VIETNAM;
			case "vo": return Icons.SPEECH_BALLOON;
			case "wo": return Icons.SPEECH_BALLOON;
			case "xh": return Icons.SPEECH_BALLOON;
			case "yi": return Icons.SPEECH_BALLOON;
			case "yo": return Icons.SPEECH_BALLOON;
			case "za": return Icons.SPEECH_BALLOON;
			case "zh": return Icons.FLAG_CHINA;
			case "zu": return Icons.SPEECH_BALLOON;
		}
		return null;
	}
}


				
				
